sat
(
  (define-fun N0_C0_E_m0r4c0_pin0 () Bool
    false)
  (define-fun N0_C0_E_m2r4c0_pin0 () Bool
    false)
  (define-fun N0_C0_E_m0r4c1_pin0 () Bool
    true)
  (define-fun N0_C0_E_m2r4c1_pin0 () Bool
    false)
  (define-fun N2_C0_E_m0r4c0_pin2 () Bool
    false)
  (define-fun N2_C0_E_m2r4c0_pin2 () Bool
    false)
  (define-fun N2_C0_E_m0r4c1_pin2 () Bool
    false)
  (define-fun N2_C0_E_m2r4c1_pin2 () Bool
    true)
  (define-fun N2_C1_E_m0r4c0_pin2 () Bool
    false)
  (define-fun N2_C1_E_m2r4c0_pin2 () Bool
    false)
  (define-fun N2_C1_E_m0r4c1_pin2 () Bool
    false)
  (define-fun N2_C1_E_m2r4c1_pin2 () Bool
    true)
  (define-fun N2_C1_E_m0r2c0_pin5 () Bool
    false)
  (define-fun N2_C1_E_m2r2c0_pin5 () Bool
    false)
  (define-fun N2_C1_E_m0r2c1_pin5 () Bool
    false)
  (define-fun N2_C1_E_m2r2c1_pin5 () Bool
    true)
  (define-fun N3_C0_E_m0r2c0_pin3 () Bool
    false)
  (define-fun N3_C0_E_m2r2c0_pin3 () Bool
    false)
  (define-fun N3_C0_E_m0r2c1_pin3 () Bool
    true)
  (define-fun N3_C0_E_m2r2c1_pin3 () Bool
    false)
  (define-fun N0_C0_E_m0r4c0_m0r4c1 () Bool
    false)
  (define-fun N0_C0_E_m0r4c0_m0r5c0 () Bool
    false)
  (define-fun N0_C0_E_m0r4c1_m0r5c1 () Bool
    true)
  (define-fun N2_E_m1r5c0_m2r5c0 () Bool
    false)
  (define-fun N0_C0_E_m0r5c0_m0r5c1 () Bool
    false)
  (define-fun N0_C0_E_m0r5c0_m0r6c0 () Bool
    false)
  (define-fun N0_C0_E_m0r5c0_m1r5c0 () Bool
    false)
  (define-fun N2_E_m2r1c0_m3r1c0 () Bool
    false)
  (define-fun N0_C0_E_m0r5c1_m0r6c1 () Bool
    true)
  (define-fun N0_C0_E_m0r5c1_m1r5c1 () Bool
    false)
  (define-fun N0_C0_E_m0r6c0_m0r6c1 () Bool
    true)
  (define-fun N0_C0_E_m0r6c0_m1r6c0 () Bool
    true)
  (define-fun N0_C0_E_m0r6c1_m1r6c1 () Bool
    false)
  (define-fun N0_C0_E_m1r5c0_m1r6c0 () Bool
    false)
  (define-fun N0_C0_E_m1r5c0_m2r5c0 () Bool
    false)
  (define-fun N0_C0_E_m1r5c1_m1r6c1 () Bool
    false)
  (define-fun N0_C0_E_m1r5c1_m2r5c1 () Bool
    false)
  (define-fun N0_C0_E_m1r6c0_m2r6c0 () Bool
    true)
  (define-fun N0_C0_E_m1r6c1_m2r6c1 () Bool
    false)
  (define-fun N0_C0_E_m2r4c0_m2r5c0 () Bool
    false)
  (define-fun N0_C0_E_m2r4c0_m3r4c0 () Bool
    false)
  (define-fun N0_C0_E_m2r4c1_m2r5c1 () Bool
    false)
  (define-fun N0_C0_E_m2r4c1_m3r4c1 () Bool
    false)
  (define-fun N2_E_m2r2c0_m2r3c0 () Bool
    false)
  (define-fun N0_C0_E_m2r5c0_m2r6c0 () Bool
    false)
  (define-fun N0_C0_E_m2r5c0_m3r5c0 () Bool
    false)
  (define-fun N2_E_m2r3c0_m2r4c0 () Bool
    false)
  (define-fun N0_C0_E_m2r5c1_m2r6c1 () Bool
    false)
  (define-fun N0_C0_E_m2r5c1_m3r5c1 () Bool
    false)
  (define-fun N0_C0_E_m2r6c0_m3r6c0 () Bool
    true)
  (define-fun N0_C0_E_m2r6c1_m3r6c1 () Bool
    false)
  (define-fun N0_C0_E_m3r4c0_m3r4c1 () Bool
    false)
  (define-fun N0_C0_E_m3r5c0_m3r5c1 () Bool
    false)
  (define-fun N0_C0_E_m3r6c0_m3r6c1 () Bool
    false)
  (define-fun N1_C0_E_m0r1c0_m0r1c1 () Bool
    false)
  (define-fun N1_C0_E_m0r1c0_m0r2c0 () Bool
    false)
  (define-fun N1_C0_E_m0r1c0_m1r1c0 () Bool
    false)
  (define-fun N1_C0_E_m0r1c1_m0r2c1 () Bool
    false)
  (define-fun N1_C0_E_m0r1c1_m1r1c1 () Bool
    false)
  (define-fun N1_C0_E_m0r2c0_m0r2c1 () Bool
    false)
  (define-fun N1_C0_E_m0r2c0_m0r3c0 () Bool
    false)
  (define-fun N1_C0_E_m0r2c1_m0r3c1 () Bool
    false)
  (define-fun N2_E_m2r4c1_m2r5c1 () Bool
    false)
  (define-fun N1_C0_E_m0r3c0_m0r3c1 () Bool
    true)
  (define-fun N1_C0_E_m0r3c0_m0r4c0 () Bool
    false)
  (define-fun N1_C0_E_m0r3c0_m1r3c0 () Bool
    true)
  (define-fun N2_E_m3r1c0_m3r1c1 () Bool
    false)
  (define-fun N1_C0_E_m0r3c1_m0r4c1 () Bool
    false)
  (define-fun N1_C0_E_m0r3c1_m1r3c1 () Bool
    true)
  (define-fun N1_C0_E_m0r4c0_m0r4c1 () Bool
    false)
  (define-fun N1_C0_E_m0r4c0_m0r5c0 () Bool
    false)
  (define-fun N1_C0_E_m0r4c1_m0r5c1 () Bool
    false)
  (define-fun N1_C0_E_m0r5c0_m0r5c1 () Bool
    false)
  (define-fun N1_C0_E_m0r5c0_m1r5c0 () Bool
    false)
  (define-fun N1_C0_E_m0r5c1_m1r5c1 () Bool
    false)
  (define-fun N1_C0_E_m1r1c0_m1r2c0 () Bool
    false)
  (define-fun N1_C0_E_m1r1c0_m2r1c0 () Bool
    false)
  (define-fun N1_C0_E_m1r1c1_m1r2c1 () Bool
    false)
  (define-fun N1_C0_E_m1r1c1_m2r1c1 () Bool
    false)
  (define-fun N1_C0_E_m1r2c0_m1r3c0 () Bool
    false)
  (define-fun N1_C0_E_m1r2c1_m1r3c1 () Bool
    false)
  (define-fun N3_E_m0r0c0_m0r1c0 () Bool
    false)
  (define-fun N1_C0_E_m1r3c0_m1r4c0 () Bool
    false)
  (define-fun N1_C0_E_m1r3c0_m2r3c0 () Bool
    true)
  (define-fun N3_E_m0r1c0_m1r1c0 () Bool
    false)
  (define-fun N1_C0_E_m1r3c1_m1r4c1 () Bool
    true)
  (define-fun N1_C0_E_m1r3c1_m2r3c1 () Bool
    false)
  (define-fun N1_C0_E_m1r4c0_m1r5c0 () Bool
    false)
  (define-fun N1_C0_E_m1r4c1_m1r5c1 () Bool
    false)
  (define-fun N1_C0_E_m1r5c0_m2r5c0 () Bool
    false)
  (define-fun N1_C0_E_m1r5c1_m2r5c1 () Bool
    false)
  (define-fun N3_E_m1r0c0_m1r1c0 () Bool
    false)
  (define-fun N1_C0_E_m2r1c0_m3r1c0 () Bool
    false)
  (define-fun N1_C0_E_m2r1c0_m2r2c0 () Bool
    false)
  (define-fun N1_C0_E_m2r1c0_pinSON () Bool
    false)
  (define-fun N3_E_m2r0c0_m2r1c0 () Bool
    false)
  (define-fun N1_C0_E_m2r1c1_m3r1c1 () Bool
    false)
  (define-fun N1_C0_E_m2r1c1_m2r2c1 () Bool
    false)
  (define-fun N1_C0_E_m2r1c1_pinSON () Bool
    false)
  (define-fun N3_E_m2r1c1_m2r2c1 () Bool
    false)
  (define-fun N1_C0_E_m2r2c0_m3r2c0 () Bool
    false)
  (define-fun N1_C0_E_m2r2c0_m2r3c0 () Bool
    false)
  (define-fun N1_C0_E_m2r2c0_pinSON () Bool
    false)
  (define-fun N3_E_m2r2c0_m3r2c0 () Bool
    false)
  (define-fun N1_C0_E_m2r2c1_m3r2c1 () Bool
    false)
  (define-fun N1_C0_E_m2r2c1_m2r3c1 () Bool
    false)
  (define-fun N1_C0_E_m2r2c1_pinSON () Bool
    false)
  (define-fun x0 () (_ BitVec 3)
    #b001)
  (define-fun N1_C0_E_m2r3c0_m3r3c0 () Bool
    false)
  (define-fun N1_C0_E_m2r3c0_m2r4c0 () Bool
    true)
  (define-fun N1_C0_E_m2r3c0_pinSON () Bool
    false)
  (define-fun N0_E_m0r3c1_m0r4c1 () Bool
    false)
  (define-fun N1_C0_E_m2r3c1_m3r3c1 () Bool
    false)
  (define-fun N1_C0_E_m2r3c1_m2r4c1 () Bool
    false)
  (define-fun N1_C0_E_m2r3c1_pinSON () Bool
    false)
  (define-fun N3_E_m1r2c1_m1r3c1 () Bool
    false)
  (define-fun N1_C0_E_m2r4c0_m3r4c0 () Bool
    false)
  (define-fun N1_C0_E_m2r4c0_m2r5c0 () Bool
    false)
  (define-fun N1_C0_E_m2r4c0_pinSON () Bool
    true)
  (define-fun N0_E_m1r4c1_m1r5c1 () Bool
    false)
  (define-fun N1_C0_E_m2r4c1_m3r4c1 () Bool
    false)
  (define-fun N1_C0_E_m2r4c1_m2r5c1 () Bool
    false)
  (define-fun N1_C0_E_m2r4c1_pinSON () Bool
    false)
  (define-fun N0_E_m2r3c1_m2r4c1 () Bool
    false)
  (define-fun N1_C0_E_m2r5c0_m3r5c0 () Bool
    false)
  (define-fun N1_C0_E_m2r5c0_pinSON () Bool
    false)
  (define-fun N1_E_m3r4c0_m3r4c1 () Bool
    false)
  (define-fun N1_C0_E_m2r5c1_m3r5c1 () Bool
    false)
  (define-fun N1_C0_E_m2r5c1_pinSON () Bool
    false)
  (define-fun N1_C0_E_m3r1c0_m3r1c1 () Bool
    false)
  (define-fun N1_C0_E_m3r2c0_m3r2c1 () Bool
    false)
  (define-fun N1_C0_E_m3r3c0_m3r3c1 () Bool
    false)
  (define-fun N1_C0_E_m3r4c0_m3r4c1 () Bool
    false)
  (define-fun N1_C0_E_m3r5c0_m3r5c1 () Bool
    false)
  (define-fun N1_C1_E_m0r1c0_m0r1c1 () Bool
    false)
  (define-fun N1_C1_E_m0r1c0_m0r2c0 () Bool
    false)
  (define-fun N1_C1_E_m0r1c0_m1r1c0 () Bool
    false)
  (define-fun N1_C1_E_m0r1c1_m0r2c1 () Bool
    false)
  (define-fun N1_C1_E_m0r1c1_m1r1c1 () Bool
    false)
  (define-fun N1_C1_E_m0r2c0_m0r2c1 () Bool
    false)
  (define-fun N1_C1_E_m0r2c0_m0r3c0 () Bool
    false)
  (define-fun N1_C1_E_m0r2c1_m0r3c1 () Bool
    false)
  (define-fun N2_E_m0r1c0_m0r1c1 () Bool
    false)
  (define-fun N1_C1_E_m0r3c0_m0r3c1 () Bool
    false)
  (define-fun N1_C1_E_m0r3c0_m0r4c0 () Bool
    false)
  (define-fun N1_C1_E_m0r3c0_m1r3c0 () Bool
    false)
  (define-fun N2_E_m0r1c0_m1r1c0 () Bool
    false)
  (define-fun N1_C1_E_m0r3c1_m0r4c1 () Bool
    false)
  (define-fun N1_C1_E_m0r3c1_m1r3c1 () Bool
    false)
  (define-fun N1_C1_E_m0r4c0_m0r4c1 () Bool
    false)
  (define-fun N1_C1_E_m0r4c0_m0r5c0 () Bool
    false)
  (define-fun N1_C1_E_m0r4c1_m0r5c1 () Bool
    false)
  (define-fun N1_C1_E_m0r5c0_m0r5c1 () Bool
    false)
  (define-fun N1_C1_E_m0r5c0_m1r5c0 () Bool
    false)
  (define-fun N1_C1_E_m0r5c1_m1r5c1 () Bool
    false)
  (define-fun N1_C1_E_m1r1c0_m1r2c0 () Bool
    false)
  (define-fun N1_C1_E_m1r1c0_m2r1c0 () Bool
    false)
  (define-fun N1_C1_E_m1r1c1_m1r2c1 () Bool
    false)
  (define-fun N1_C1_E_m1r1c1_m2r1c1 () Bool
    false)
  (define-fun N1_C1_E_m1r2c0_m1r3c0 () Bool
    false)
  (define-fun N1_C1_E_m1r2c1_m1r3c1 () Bool
    true)
  (define-fun N2_E_m0r1c1_m1r1c1 () Bool
    false)
  (define-fun N1_C1_E_m1r3c0_m1r4c0 () Bool
    false)
  (define-fun N1_C1_E_m1r3c0_m2r3c0 () Bool
    false)
  (define-fun N0_E_m1r4c0_m1r5c0 () Bool
    false)
  (define-fun N1_C1_E_m1r3c1_m1r4c1 () Bool
    true)
  (define-fun N1_C1_E_m1r3c1_m2r3c1 () Bool
    false)
  (define-fun N1_C1_E_m1r4c0_m1r5c0 () Bool
    false)
  (define-fun N1_C1_E_m1r4c1_m1r5c1 () Bool
    false)
  (define-fun N1_C1_E_m1r5c0_m2r5c0 () Bool
    false)
  (define-fun N1_C1_E_m1r5c1_m2r5c1 () Bool
    false)
  (define-fun N1_C1_E_m2r1c0_m3r1c0 () Bool
    false)
  (define-fun N1_C1_E_m2r1c0_m2r2c0 () Bool
    false)
  (define-fun N1_C1_E_m2r1c1_m3r1c1 () Bool
    false)
  (define-fun N1_C1_E_m2r1c1_m2r2c1 () Bool
    false)
  (define-fun N1_C1_E_m2r2c0_m3r2c0 () Bool
    false)
  (define-fun N1_C1_E_m2r2c0_m2r3c0 () Bool
    false)
  (define-fun N1_C1_E_m2r2c1_m3r2c1 () Bool
    false)
  (define-fun N1_C1_E_m2r2c1_m2r3c1 () Bool
    false)
  (define-fun N3_E_m1r2c0_m1r3c0 () Bool
    false)
  (define-fun N1_C1_E_m2r3c0_m3r3c0 () Bool
    false)
  (define-fun N1_C1_E_m2r3c0_m2r4c0 () Bool
    false)
  (define-fun N2_E_m0r2c0_m0r3c0 () Bool
    false)
  (define-fun N1_C1_E_m2r3c1_m3r3c1 () Bool
    false)
  (define-fun N1_C1_E_m2r3c1_m2r4c1 () Bool
    false)
  (define-fun N1_C1_E_m2r4c0_m3r4c0 () Bool
    false)
  (define-fun N1_C1_E_m2r4c0_m2r5c0 () Bool
    false)
  (define-fun N1_C1_E_m2r4c1_m3r4c1 () Bool
    false)
  (define-fun N1_C1_E_m2r4c1_m2r5c1 () Bool
    false)
  (define-fun N1_C1_E_m2r5c0_m3r5c0 () Bool
    false)
  (define-fun N1_C1_E_m2r5c1_m3r5c1 () Bool
    false)
  (define-fun N1_C1_E_m3r1c0_m3r1c1 () Bool
    false)
  (define-fun N1_C1_E_m3r2c0_m3r2c1 () Bool
    false)
  (define-fun N1_C1_E_m3r3c0_m3r3c1 () Bool
    false)
  (define-fun N1_C1_E_m3r4c0_m3r4c1 () Bool
    false)
  (define-fun N1_C1_E_m3r5c0_m3r5c1 () Bool
    false)
  (define-fun N2_C0_E_m0r1c0_m0r1c1 () Bool
    false)
  (define-fun N2_C0_E_m0r1c0_m0r2c0 () Bool
    false)
  (define-fun N2_C0_E_m0r1c0_m1r1c0 () Bool
    false)
  (define-fun N2_C0_E_m0r1c1_m0r2c1 () Bool
    false)
  (define-fun N2_C0_E_m0r1c1_m1r1c1 () Bool
    false)
  (define-fun N2_C0_E_m0r2c0_m0r2c1 () Bool
    false)
  (define-fun N2_C0_E_m0r2c0_m0r3c0 () Bool
    false)
  (define-fun N2_C0_E_m0r2c1_m0r3c1 () Bool
    false)
  (define-fun N2_E_m0r3c0_m0r3c1 () Bool
    false)
  (define-fun N2_C0_E_m0r3c0_m0r3c1 () Bool
    false)
  (define-fun N2_C0_E_m0r3c0_m0r4c0 () Bool
    false)
  (define-fun N2_C0_E_m0r3c0_m1r3c0 () Bool
    false)
  (define-fun N2_E_m0r3c0_m1r3c0 () Bool
    false)
  (define-fun N2_C0_E_m0r3c1_m0r4c1 () Bool
    false)
  (define-fun N2_C0_E_m0r3c1_m1r3c1 () Bool
    false)
  (define-fun N2_E_m0r3c1_m1r3c1 () Bool
    false)
  (define-fun N2_C0_E_m0r4c0_m0r4c1 () Bool
    false)
  (define-fun N2_C0_E_m0r4c0_m0r5c0 () Bool
    false)
  (define-fun N2_E_m0r4c0_m0r5c0 () Bool
    false)
  (define-fun N2_C0_E_m0r4c1_m0r5c1 () Bool
    false)
  (define-fun N2_C0_E_m0r5c0_m0r5c1 () Bool
    false)
  (define-fun N2_C0_E_m0r5c0_m1r5c0 () Bool
    false)
  (define-fun N2_C0_E_m0r5c1_m1r5c1 () Bool
    false)
  (define-fun N2_C0_E_m1r1c0_m1r2c0 () Bool
    false)
  (define-fun N2_C0_E_m1r1c0_m2r1c0 () Bool
    false)
  (define-fun N2_C0_E_m1r1c1_m1r2c1 () Bool
    false)
  (define-fun N2_C0_E_m1r1c1_m2r1c1 () Bool
    false)
  (define-fun N2_C0_E_m1r2c0_m1r3c0 () Bool
    false)
  (define-fun N2_C0_E_m1r2c1_m1r3c1 () Bool
    false)
  (define-fun N2_E_m0r5c0_m0r5c1 () Bool
    false)
  (define-fun N2_C0_E_m1r3c0_m1r4c0 () Bool
    false)
  (define-fun N2_C0_E_m1r3c0_m2r3c0 () Bool
    false)
  (define-fun N2_E_m0r5c1_m1r5c1 () Bool
    false)
  (define-fun N2_C0_E_m1r3c1_m1r4c1 () Bool
    false)
  (define-fun N2_C0_E_m1r3c1_m2r3c1 () Bool
    false)
  (define-fun N2_C0_E_m1r4c0_m1r5c0 () Bool
    false)
  (define-fun N2_C0_E_m1r4c1_m1r5c1 () Bool
    false)
  (define-fun N2_C0_E_m1r5c0_m2r5c0 () Bool
    false)
  (define-fun N2_C0_E_m1r5c1_m2r5c1 () Bool
    false)
  (define-fun N2_E_m1r1c0_m2r1c0 () Bool
    false)
  (define-fun N2_C0_E_m2r1c0_m3r1c0 () Bool
    false)
  (define-fun N2_C0_E_m2r1c0_m2r2c0 () Bool
    false)
  (define-fun N2_C0_E_m2r1c0_pinSON () Bool
    false)
  (define-fun N2_E_m1r1c1_m2r1c1 () Bool
    false)
  (define-fun N2_C0_E_m2r1c1_m3r1c1 () Bool
    false)
  (define-fun N2_C0_E_m2r1c1_m2r2c1 () Bool
    false)
  (define-fun N2_C0_E_m2r1c1_pinSON () Bool
    false)
  (define-fun N2_E_m1r2c1_m1r3c1 () Bool
    false)
  (define-fun N2_C0_E_m2r2c0_m3r2c0 () Bool
    false)
  (define-fun N2_C0_E_m2r2c0_m2r3c0 () Bool
    false)
  (define-fun N2_C0_E_m2r2c0_pinSON () Bool
    false)
  (define-fun N2_E_m1r3c0_m2r3c0 () Bool
    false)
  (define-fun N2_C0_E_m2r2c1_m3r2c1 () Bool
    false)
  (define-fun N2_C0_E_m2r2c1_m2r3c1 () Bool
    true)
  (define-fun N2_C0_E_m2r2c1_pinSON () Bool
    true)
  (define-fun N2_E_m1r4c0_m1r5c0 () Bool
    false)
  (define-fun N2_C0_E_m2r3c0_m3r3c0 () Bool
    false)
  (define-fun N2_C0_E_m2r3c0_m2r4c0 () Bool
    false)
  (define-fun N2_C0_E_m2r3c0_pinSON () Bool
    false)
  (define-fun N2_E_m1r5c1_m2r5c1 () Bool
    false)
  (define-fun N2_C0_E_m2r3c1_m3r3c1 () Bool
    false)
  (define-fun N2_C0_E_m2r3c1_m2r4c1 () Bool
    true)
  (define-fun N2_C0_E_m2r3c1_pinSON () Bool
    false)
  (define-fun N2_E_m2r1c1_m2r2c1 () Bool
    false)
  (define-fun N2_C0_E_m2r4c0_m3r4c0 () Bool
    false)
  (define-fun N2_C0_E_m2r4c0_m2r5c0 () Bool
    false)
  (define-fun N2_C0_E_m2r4c0_pinSON () Bool
    false)
  (define-fun N2_E_m2r2c0_m3r2c0 () Bool
    false)
  (define-fun N2_C0_E_m2r4c1_m3r4c1 () Bool
    false)
  (define-fun N2_C0_E_m2r4c1_m2r5c1 () Bool
    false)
  (define-fun N2_C0_E_m2r4c1_pinSON () Bool
    false)
  (define-fun N2_E_m2r2c1_m3r2c1 () Bool
    false)
  (define-fun N2_C0_E_m2r5c0_m3r5c0 () Bool
    false)
  (define-fun N2_C0_E_m2r5c0_pinSON () Bool
    false)
  (define-fun N2_E_m2r3c1_m2r4c1 () Bool
    true)
  (define-fun N2_C0_E_m2r5c1_m3r5c1 () Bool
    false)
  (define-fun N2_C0_E_m2r5c1_pinSON () Bool
    false)
  (define-fun N2_C0_E_m3r1c0_m3r1c1 () Bool
    false)
  (define-fun N2_C0_E_m3r2c0_m3r2c1 () Bool
    false)
  (define-fun N2_C0_E_m3r3c0_m3r3c1 () Bool
    false)
  (define-fun N2_C0_E_m3r4c0_m3r4c1 () Bool
    false)
  (define-fun N2_C0_E_m3r5c0_m3r5c1 () Bool
    false)
  (define-fun N2_C1_E_m0r1c0_m0r1c1 () Bool
    false)
  (define-fun N2_C1_E_m0r1c0_m0r2c0 () Bool
    false)
  (define-fun N2_C1_E_m0r1c0_m1r1c0 () Bool
    false)
  (define-fun N2_C1_E_m0r1c1_m0r2c1 () Bool
    false)
  (define-fun N2_C1_E_m0r1c1_m1r1c1 () Bool
    false)
  (define-fun N2_E_m2r4c0_m3r4c0 () Bool
    false)
  (define-fun N2_C1_E_m0r2c0_m0r2c1 () Bool
    false)
  (define-fun N2_C1_E_m0r2c0_m0r3c0 () Bool
    false)
  (define-fun N2_E_m2r4c1_m3r4c1 () Bool
    false)
  (define-fun N2_C1_E_m0r2c1_m0r3c1 () Bool
    false)
  (define-fun N2_E_m2r5c1_m3r5c1 () Bool
    false)
  (define-fun N2_C1_E_m0r3c0_m0r3c1 () Bool
    false)
  (define-fun N2_C1_E_m0r3c0_m0r4c0 () Bool
    false)
  (define-fun N2_C1_E_m0r3c0_m1r3c0 () Bool
    false)
  (define-fun N2_E_m3r2c0_m3r2c1 () Bool
    false)
  (define-fun N2_C1_E_m0r3c1_m0r4c1 () Bool
    false)
  (define-fun N2_C1_E_m0r3c1_m1r3c1 () Bool
    false)
  (define-fun N2_E_m3r5c0_m3r5c1 () Bool
    false)
  (define-fun N2_C1_E_m0r4c0_m0r4c1 () Bool
    false)
  (define-fun N2_C1_E_m0r4c0_m0r5c0 () Bool
    false)
  (define-fun N3_E_m0r0c1_m0r1c1 () Bool
    true)
  (define-fun N2_C1_E_m0r4c1_m0r5c1 () Bool
    false)
  (define-fun N2_C1_E_m0r5c0_m0r5c1 () Bool
    false)
  (define-fun N2_C1_E_m0r5c0_m1r5c0 () Bool
    false)
  (define-fun N2_C1_E_m0r5c1_m1r5c1 () Bool
    false)
  (define-fun N2_C1_E_m1r1c0_m1r2c0 () Bool
    false)
  (define-fun N2_C1_E_m1r1c0_m2r1c0 () Bool
    false)
  (define-fun N2_C1_E_m1r1c1_m1r2c1 () Bool
    false)
  (define-fun N2_C1_E_m1r1c1_m2r1c1 () Bool
    false)
  (define-fun N2_C1_E_m1r2c0_m1r3c0 () Bool
    false)
  (define-fun N2_C1_E_m1r2c1_m1r3c1 () Bool
    false)
  (define-fun N3_E_m0r1c0_m0r2c0 () Bool
    false)
  (define-fun N2_C1_E_m1r3c0_m1r4c0 () Bool
    false)
  (define-fun N2_C1_E_m1r3c0_m2r3c0 () Bool
    false)
  (define-fun N3_E_m0r1c1_m0r2c1 () Bool
    true)
  (define-fun N2_C1_E_m1r3c1_m1r4c1 () Bool
    false)
  (define-fun N2_C1_E_m1r3c1_m2r3c1 () Bool
    false)
  (define-fun N2_C1_E_m1r4c0_m1r5c0 () Bool
    false)
  (define-fun N2_C1_E_m1r4c1_m1r5c1 () Bool
    false)
  (define-fun N2_C1_E_m1r5c0_m2r5c0 () Bool
    false)
  (define-fun N2_C1_E_m1r5c1_m2r5c1 () Bool
    false)
  (define-fun N2_C1_E_m2r1c0_m3r1c0 () Bool
    false)
  (define-fun N2_C1_E_m2r1c0_m2r2c0 () Bool
    false)
  (define-fun N2_C1_E_m2r1c1_m3r1c1 () Bool
    false)
  (define-fun N2_C1_E_m2r1c1_m2r2c1 () Bool
    false)
  (define-fun N3_E_m0r2c0_m0r2c1 () Bool
    false)
  (define-fun N2_C1_E_m2r2c0_m3r2c0 () Bool
    false)
  (define-fun N2_C1_E_m2r2c0_m2r3c0 () Bool
    false)
  (define-fun N3_E_m1r0c1_m1r1c1 () Bool
    false)
  (define-fun N2_C1_E_m2r2c1_m3r2c1 () Bool
    false)
  (define-fun N2_C1_E_m2r2c1_m2r3c1 () Bool
    true)
  (define-fun N3_E_m1r1c1_m2r1c1 () Bool
    false)
  (define-fun N2_C1_E_m2r3c0_m3r3c0 () Bool
    false)
  (define-fun N2_C1_E_m2r3c0_m2r4c0 () Bool
    false)
  (define-fun N3_E_m2r0c1_m2r1c1 () Bool
    false)
  (define-fun N2_C1_E_m2r3c1_m3r3c1 () Bool
    false)
  (define-fun N2_C1_E_m2r3c1_m2r4c1 () Bool
    true)
  (define-fun N3_E_m2r1c0_m3r1c0 () Bool
    false)
  (define-fun N2_C1_E_m2r4c0_m3r4c0 () Bool
    false)
  (define-fun N2_C1_E_m2r4c0_m2r5c0 () Bool
    false)
  (define-fun N0_E_m2r3c0_m2r4c0 () Bool
    false)
  (define-fun N2_C1_E_m2r4c1_m3r4c1 () Bool
    false)
  (define-fun N2_C1_E_m2r4c1_m2r5c1 () Bool
    false)
  (define-fun N2_C1_E_m2r5c0_m3r5c0 () Bool
    false)
  (define-fun N2_C1_E_m2r5c1_m3r5c1 () Bool
    false)
  (define-fun N2_C1_E_m3r1c0_m3r1c1 () Bool
    false)
  (define-fun N2_C1_E_m3r2c0_m3r2c1 () Bool
    false)
  (define-fun N2_C1_E_m3r3c0_m3r3c1 () Bool
    false)
  (define-fun N2_C1_E_m3r4c0_m3r4c1 () Bool
    false)
  (define-fun N2_C1_E_m3r5c0_m3r5c1 () Bool
    false)
  (define-fun N3_C0_E_m0r0c0_m0r0c1 () Bool
    true)
  (define-fun N3_C0_E_m0r0c0_m0r1c0 () Bool
    false)
  (define-fun N3_C0_E_m0r0c0_m1r0c0 () Bool
    true)
  (define-fun N3_C0_E_m0r0c1_m0r1c1 () Bool
    true)
  (define-fun N3_C0_E_m0r0c1_m1r0c1 () Bool
    false)
  (define-fun N3_E_m2r1c1_m3r1c1 () Bool
    false)
  (define-fun N3_C0_E_m0r1c0_m0r1c1 () Bool
    false)
  (define-fun N3_C0_E_m0r1c0_m0r2c0 () Bool
    false)
  (define-fun N3_C0_E_m0r1c0_m1r1c0 () Bool
    false)
  (define-fun N3_E_m2r2c1_m3r2c1 () Bool
    false)
  (define-fun N3_C0_E_m0r1c1_m0r2c1 () Bool
    true)
  (define-fun N3_C0_E_m0r1c1_m1r1c1 () Bool
    false)
  (define-fun N3_C0_E_m0r2c0_m0r2c1 () Bool
    false)
  (define-fun N3_C0_E_m1r0c0_m1r1c0 () Bool
    false)
  (define-fun N3_C0_E_m1r0c0_m2r0c0 () Bool
    true)
  (define-fun N3_C0_E_m1r0c1_m1r1c1 () Bool
    false)
  (define-fun N3_C0_E_m1r0c1_m2r0c1 () Bool
    false)
  (define-fun N3_C0_E_m1r1c0_m2r1c0 () Bool
    false)
  (define-fun N3_C0_E_m1r1c1_m2r1c1 () Bool
    false)
  (define-fun N3_C0_E_m2r0c0_m2r1c0 () Bool
    false)
  (define-fun N3_C0_E_m2r0c0_m3r0c0 () Bool
    true)
  (define-fun N3_C0_E_m2r0c1_m2r1c1 () Bool
    false)
  (define-fun N3_C0_E_m2r0c1_m3r0c1 () Bool
    false)
  (define-fun N3_E_m3r2c0_m3r2c1 () Bool
    false)
  (define-fun N3_C0_E_m2r1c0_m2r2c0 () Bool
    false)
  (define-fun N3_C0_E_m2r1c0_m3r1c0 () Bool
    false)
  (define-fun N3_E_m0r2c1_m0r3c1 () Bool
    false)
  (define-fun N3_C0_E_m2r1c1_m2r2c1 () Bool
    false)
  (define-fun N3_C0_E_m2r1c1_m3r1c1 () Bool
    false)
  (define-fun N3_C0_E_m2r2c0_m3r2c0 () Bool
    false)
  (define-fun N3_C0_E_m2r2c1_m3r2c1 () Bool
    false)
  (define-fun N3_C0_E_m3r0c0_m3r0c1 () Bool
    false)
  (define-fun N3_C0_E_m3r1c0_m3r1c1 () Bool
    false)
  (define-fun N3_C0_E_m3r2c0_m3r2c1 () Bool
    false)
  (define-fun N3_E_m1r1c1_m1r2c1 () Bool
    false)
  (define-fun N0_E_m1r3c1_m1r4c1 () Bool
    false)
  (define-fun N0_E_m0r3c0_m0r4c0 () Bool
    false)
  (define-fun N3_E_m0r2c0_m0r3c0 () Bool
    false)
  (define-fun N3_E_m2r2c1_m2r3c1 () Bool
    false)
  (define-fun N1_E_m3r2c0_m3r2c1 () Bool
    false)
  (define-fun N1_E_m3r5c0_m3r5c1 () Bool
    false)
  (define-fun N2_E_m0r1c0_m0r2c0 () Bool
    false)
  (define-fun N2_E_m0r1c1_m0r2c1 () Bool
    false)
  (define-fun N2_E_m0r2c0_m0r2c1 () Bool
    false)
  (define-fun N0_E_m1r3c0_m1r4c0 () Bool
    false)
  (define-fun N3_E_m1r1c0_m1r2c0 () Bool
    false)
  (define-fun N2_E_m0r2c1_m0r3c1 () Bool
    false)
  (define-fun N2_E_m0r3c0_m0r4c0 () Bool
    false)
  (define-fun N2_E_m0r3c1_m0r4c1 () Bool
    false)
  (define-fun N2_E_m0r4c0_m0r4c1 () Bool
    false)
  (define-fun N2_E_m0r4c1_m0r5c1 () Bool
    false)
  (define-fun N2_E_m0r5c0_m1r5c0 () Bool
    false)
  (define-fun N2_E_m1r1c0_m1r2c0 () Bool
    false)
  (define-fun N2_E_m1r1c1_m1r2c1 () Bool
    false)
  (define-fun N2_E_m1r2c0_m1r3c0 () Bool
    false)
  (define-fun N2_E_m1r3c0_m1r4c0 () Bool
    false)
  (define-fun N2_E_m1r3c1_m1r4c1 () Bool
    false)
  (define-fun N2_E_m1r3c1_m2r3c1 () Bool
    false)
  (define-fun N2_E_m1r4c1_m1r5c1 () Bool
    false)
  (define-fun N2_E_m2r1c0_m2r2c0 () Bool
    false)
  (define-fun N2_E_m2r1c1_m3r1c1 () Bool
    false)
  (define-fun N2_E_m2r2c1_m2r3c1 () Bool
    true)
  (define-fun N2_E_m2r4c0_m2r5c0 () Bool
    false)
  (define-fun N2_E_m2r5c0_m3r5c0 () Bool
    false)
  (define-fun N2_E_m3r4c0_m3r4c1 () Bool
    false)
  (define-fun N3_E_m0r1c0_m0r1c1 () Bool
    false)
  (define-fun N3_E_m0r1c1_m1r1c1 () Bool
    false)
  (define-fun N3_E_m1r1c0_m2r1c0 () Bool
    false)
  (define-fun N1_E_m2r3c0_m3r3c0 () Bool
    false)
  (define-fun N1_E_m3r3c0_m3r3c1 () Bool
    false)
  (define-fun N2_E_m2r3c0_m3r3c0 () Bool
    false)
  (define-fun N2_E_m3r3c0_m3r3c1 () Bool
    false)
  (define-fun N1_E_m2r3c1_m3r3c1 () Bool
    false)
  (define-fun N2_E_m2r3c1_m3r3c1 () Bool
    false)
  (define-fun N3_E_m2r1c0_m2r2c0 () Bool
    false)
  (define-fun N3_E_m2r2c0_m2r3c0 () Bool
    false)
  (define-fun x1 () (_ BitVec 3)
    #b001)
  (define-fun N3_E_m3r1c0_m3r1c1 () Bool
    false)
  (define-fun N0_E_m0r4c0_m0r4c1 () Bool
    false)
  (define-fun N0_E_m0r4c0_m0r5c0 () Bool
    false)
  (define-fun N0_E_m0r4c1_m0r5c1 () Bool
    true)
  (define-fun N0_E_m0r5c0_m0r5c1 () Bool
    false)
  (define-fun N0_E_m0r5c0_m0r6c0 () Bool
    false)
  (define-fun N0_E_m0r5c0_m1r5c0 () Bool
    false)
  (define-fun N0_E_m0r5c1_m0r6c1 () Bool
    true)
  (define-fun N0_E_m0r5c1_m1r5c1 () Bool
    false)
  (define-fun N0_E_m1r5c0_m1r6c0 () Bool
    false)
  (define-fun N0_E_m1r5c0_m2r5c0 () Bool
    false)
  (define-fun N0_E_m1r5c1_m1r6c1 () Bool
    false)
  (define-fun N0_E_m1r5c1_m2r5c1 () Bool
    false)
  (define-fun N0_E_m2r4c0_m2r5c0 () Bool
    false)
  (define-fun N0_E_m2r4c0_m3r4c0 () Bool
    false)
  (define-fun N0_E_m2r4c1_m2r5c1 () Bool
    false)
  (define-fun N0_E_m2r4c1_m3r4c1 () Bool
    false)
  (define-fun N0_E_m2r5c0_m2r6c0 () Bool
    false)
  (define-fun N0_E_m2r5c0_m3r5c0 () Bool
    false)
  (define-fun N0_E_m2r5c1_m2r6c1 () Bool
    false)
  (define-fun N0_E_m2r5c1_m3r5c1 () Bool
    false)
  (define-fun N0_E_m3r4c0_m3r4c1 () Bool
    false)
  (define-fun N0_E_m3r5c0_m3r5c1 () Bool
    false)
  (define-fun N1_E_m0r1c0_m0r1c1 () Bool
    false)
  (define-fun N1_E_m0r1c0_m0r2c0 () Bool
    false)
  (define-fun N1_E_m0r1c0_m1r1c0 () Bool
    false)
  (define-fun N1_E_m0r1c1_m0r2c1 () Bool
    false)
  (define-fun N1_E_m0r1c1_m1r1c1 () Bool
    false)
  (define-fun N1_E_m0r2c0_m0r2c1 () Bool
    false)
  (define-fun N1_E_m0r2c0_m0r3c0 () Bool
    false)
  (define-fun N1_E_m0r2c1_m0r3c1 () Bool
    false)
  (define-fun N1_E_m0r3c0_m0r3c1 () Bool
    true)
  (define-fun N1_E_m0r3c0_m0r4c0 () Bool
    false)
  (define-fun N1_E_m0r3c0_m1r3c0 () Bool
    true)
  (define-fun N1_E_m0r3c1_m0r4c1 () Bool
    false)
  (define-fun N1_E_m0r3c1_m1r3c1 () Bool
    true)
  (define-fun N1_E_m0r4c0_m0r4c1 () Bool
    false)
  (define-fun N1_E_m0r4c0_m0r5c0 () Bool
    false)
  (define-fun N1_E_m0r4c1_m0r5c1 () Bool
    false)
  (define-fun N1_E_m0r5c0_m0r5c1 () Bool
    false)
  (define-fun N1_E_m0r5c0_m1r5c0 () Bool
    false)
  (define-fun N1_E_m0r5c1_m1r5c1 () Bool
    false)
  (define-fun N1_E_m1r1c0_m1r2c0 () Bool
    false)
  (define-fun N1_E_m1r1c0_m2r1c0 () Bool
    false)
  (define-fun N1_E_m1r1c1_m1r2c1 () Bool
    false)
  (define-fun N1_E_m1r1c1_m2r1c1 () Bool
    false)
  (define-fun N1_E_m1r2c0_m1r3c0 () Bool
    false)
  (define-fun N1_E_m1r2c1_m1r3c1 () Bool
    true)
  (define-fun N1_E_m1r3c0_m1r4c0 () Bool
    false)
  (define-fun N1_E_m1r3c0_m2r3c0 () Bool
    true)
  (define-fun N1_E_m1r3c1_m1r4c1 () Bool
    true)
  (define-fun N1_E_m1r3c1_m2r3c1 () Bool
    false)
  (define-fun N1_E_m1r4c0_m1r5c0 () Bool
    false)
  (define-fun N1_E_m1r4c1_m1r5c1 () Bool
    false)
  (define-fun N1_E_m1r5c0_m2r5c0 () Bool
    false)
  (define-fun N1_E_m1r5c1_m2r5c1 () Bool
    false)
  (define-fun N1_E_m2r1c0_m2r2c0 () Bool
    false)
  (define-fun N1_E_m2r1c0_m3r1c0 () Bool
    false)
  (define-fun N1_E_m2r1c1_m2r2c1 () Bool
    false)
  (define-fun N1_E_m2r1c1_m3r1c1 () Bool
    false)
  (define-fun N1_E_m2r2c0_m2r3c0 () Bool
    false)
  (define-fun N1_E_m2r2c0_m3r2c0 () Bool
    false)
  (define-fun N1_E_m2r2c1_m2r3c1 () Bool
    false)
  (define-fun N1_E_m2r2c1_m3r2c1 () Bool
    false)
  (define-fun N1_E_m2r3c0_m2r4c0 () Bool
    true)
  (define-fun N1_E_m2r3c1_m2r4c1 () Bool
    false)
  (define-fun N1_E_m2r4c0_m2r5c0 () Bool
    false)
  (define-fun N1_E_m2r4c0_m3r4c0 () Bool
    false)
  (define-fun N1_E_m2r4c1_m2r5c1 () Bool
    false)
  (define-fun N1_E_m2r4c1_m3r4c1 () Bool
    false)
  (define-fun N1_E_m2r5c0_m3r5c0 () Bool
    false)
  (define-fun N1_E_m2r5c1_m3r5c1 () Bool
    false)
  (define-fun N1_E_m3r1c0_m3r1c1 () Bool
    false)
  (define-fun N2_R5 () (_ BitVec 5)
    #b00000)
  (define-fun N2_R4 () (_ BitVec 5)
    #b00000)
  (define-fun N2_R3 () (_ BitVec 5)
    #b00000)
  (define-fun N2_R2 () (_ BitVec 5)
    #b00000)
  (define-fun N2_R1 () (_ BitVec 5)
    #b00000)
  (define-fun N2_C1 () (_ BitVec 4)
    #x1)
  (define-fun N2_C0 () (_ BitVec 4)
    #x0)
  (define-fun N1_R5 () (_ BitVec 5)
    #b00000)
  (define-fun N1_R4 () (_ BitVec 5)
    #b00000)
  (define-fun N1_R3 () (_ BitVec 5)
    #b00000)
  (define-fun N1_R2 () (_ BitVec 5)
    #b00000)
  (define-fun N1_R1 () (_ BitVec 5)
    #b00000)
  (define-fun N1_C1 () (_ BitVec 4)
    #x0)
  (define-fun N1_C0 () (_ BitVec 4)
    #x1)
  (define-fun N2_R5_EN () Bool
    false)
  (define-fun N2_R4_EN () Bool
    false)
  (define-fun N2_R3_EN () Bool
    false)
  (define-fun N2_R2_EN () Bool
    true)
  (define-fun N2_R1_EN () Bool
    false)
  (define-fun N2_C1_EN () Bool
    true)
  (define-fun N2_C0_EN () Bool
    false)
  (define-fun N1_R5_EN () Bool
    false)
  (define-fun N1_R4_EN () Bool
    true)
  (define-fun N1_R3_EN () Bool
    false)
  (define-fun N1_R2_EN () Bool
    false)
  (define-fun N1_R1_EN () Bool
    false)
  (define-fun N1_C1_EN () Bool
    false)
  (define-fun N1_C0_EN () Bool
    true)
  (define-fun N3_E_m3r6c0_m3r6c1 () Bool
    false)
  (define-fun N3_E_m3r5c0_m3r5c1 () Bool
    false)
  (define-fun N3_E_m3r4c0_m3r4c1 () Bool
    false)
  (define-fun N3_E_m3r3c0_m3r3c1 () Bool
    false)
  (define-fun N3_E_m2r6c1_m3r6c1 () Bool
    false)
  (define-fun N3_E_m2r6c0_m3r6c0 () Bool
    false)
  (define-fun N3_E_m2r5c1_m3r5c1 () Bool
    false)
  (define-fun N3_E_m2r5c1_m2r6c1 () Bool
    false)
  (define-fun N3_E_m2r5c0_m3r5c0 () Bool
    false)
  (define-fun N3_E_m2r5c0_m2r6c0 () Bool
    false)
  (define-fun N3_E_m2r4c1_m3r4c1 () Bool
    false)
  (define-fun N3_E_m2r4c1_m2r5c1 () Bool
    false)
  (define-fun N3_E_m2r4c0_m3r4c0 () Bool
    false)
  (define-fun N3_E_m2r4c0_m2r5c0 () Bool
    false)
  (define-fun N3_E_m2r3c1_m3r3c1 () Bool
    false)
  (define-fun N3_E_m2r3c1_m2r4c1 () Bool
    false)
  (define-fun N3_E_m2r3c0_m3r3c0 () Bool
    false)
  (define-fun N3_E_m2r3c0_m2r4c0 () Bool
    false)
  (define-fun N3_E_m1r6c1_m2r6c1 () Bool
    false)
  (define-fun N3_E_m1r6c0_m2r6c0 () Bool
    false)
  (define-fun N3_E_m1r5c1_m2r5c1 () Bool
    false)
  (define-fun N3_E_m1r5c1_m1r6c1 () Bool
    false)
  (define-fun N3_E_m1r5c0_m2r5c0 () Bool
    false)
  (define-fun N3_E_m1r5c0_m1r6c0 () Bool
    false)
  (define-fun N3_E_m1r4c1_m1r5c1 () Bool
    false)
  (define-fun N3_E_m1r4c0_m1r5c0 () Bool
    false)
  (define-fun N3_E_m1r3c1_m2r3c1 () Bool
    false)
  (define-fun N3_E_m1r3c1_m1r4c1 () Bool
    false)
  (define-fun N3_E_m1r3c0_m2r3c0 () Bool
    false)
  (define-fun N3_E_m1r3c0_m1r4c0 () Bool
    false)
  (define-fun N3_E_m0r6c1_m1r6c1 () Bool
    false)
  (define-fun N3_E_m0r6c0_m1r6c0 () Bool
    false)
  (define-fun N3_E_m0r6c0_m0r6c1 () Bool
    false)
  (define-fun N3_E_m0r5c1_m1r5c1 () Bool
    false)
  (define-fun N3_E_m0r5c1_m0r6c1 () Bool
    false)
  (define-fun N3_E_m0r5c0_m1r5c0 () Bool
    false)
  (define-fun N3_E_m0r5c0_m0r6c0 () Bool
    false)
  (define-fun N3_E_m0r5c0_m0r5c1 () Bool
    false)
  (define-fun N3_E_m0r4c1_m0r5c1 () Bool
    false)
  (define-fun N3_E_m0r4c0_m0r5c0 () Bool
    false)
  (define-fun N3_E_m0r4c0_m0r4c1 () Bool
    false)
  (define-fun N3_E_m0r3c1_m1r3c1 () Bool
    false)
  (define-fun N3_E_m0r3c1_m0r4c1 () Bool
    false)
  (define-fun N3_E_m0r3c0_m1r3c0 () Bool
    false)
  (define-fun N3_E_m0r3c0_m0r4c0 () Bool
    false)
  (define-fun N3_E_m0r3c0_m0r3c1 () Bool
    false)
  (define-fun N0_E_m3r3c0_m3r3c1 () Bool
    false)
  (define-fun N0_E_m3r2c0_m3r2c1 () Bool
    false)
  (define-fun N0_E_m3r1c0_m3r1c1 () Bool
    false)
  (define-fun N0_E_m3r0c0_m3r0c1 () Bool
    false)
  (define-fun N0_E_m2r3c1_m3r3c1 () Bool
    false)
  (define-fun N0_E_m2r3c0_m3r3c0 () Bool
    false)
  (define-fun N0_E_m2r2c1_m3r2c1 () Bool
    false)
  (define-fun N0_E_m2r2c1_m2r3c1 () Bool
    false)
  (define-fun N0_E_m2r2c0_m3r2c0 () Bool
    false)
  (define-fun N0_E_m2r2c0_m2r3c0 () Bool
    false)
  (define-fun N0_E_m2r1c1_m3r1c1 () Bool
    false)
  (define-fun N0_E_m2r1c1_m2r2c1 () Bool
    false)
  (define-fun N0_E_m2r1c0_m3r1c0 () Bool
    false)
  (define-fun N0_E_m2r1c0_m2r2c0 () Bool
    false)
  (define-fun N0_E_m2r0c1_m3r0c1 () Bool
    false)
  (define-fun N0_E_m2r0c1_m2r1c1 () Bool
    false)
  (define-fun N0_E_m2r0c0_m3r0c0 () Bool
    false)
  (define-fun N0_E_m2r0c0_m2r1c0 () Bool
    false)
  (define-fun N0_E_m1r3c1_m2r3c1 () Bool
    false)
  (define-fun N0_E_m1r3c0_m2r3c0 () Bool
    false)
  (define-fun N0_E_m1r2c1_m1r3c1 () Bool
    false)
  (define-fun N0_E_m1r2c0_m1r3c0 () Bool
    false)
  (define-fun N0_E_m1r1c1_m2r1c1 () Bool
    false)
  (define-fun N0_E_m1r1c1_m1r2c1 () Bool
    false)
  (define-fun N0_E_m1r1c0_m2r1c0 () Bool
    false)
  (define-fun N0_E_m1r1c0_m1r2c0 () Bool
    false)
  (define-fun N0_E_m1r0c1_m2r0c1 () Bool
    false)
  (define-fun N0_E_m1r0c1_m1r1c1 () Bool
    false)
  (define-fun N0_E_m1r0c0_m2r0c0 () Bool
    false)
  (define-fun N0_E_m1r0c0_m1r1c0 () Bool
    false)
  (define-fun N0_E_m0r3c1_m1r3c1 () Bool
    false)
  (define-fun N0_E_m0r3c0_m1r3c0 () Bool
    false)
  (define-fun N0_E_m0r3c0_m0r3c1 () Bool
    false)
  (define-fun N0_E_m0r2c1_m0r3c1 () Bool
    false)
  (define-fun N0_E_m0r2c0_m0r3c0 () Bool
    false)
  (define-fun N0_E_m0r2c0_m0r2c1 () Bool
    false)
  (define-fun N0_E_m0r1c1_m1r1c1 () Bool
    false)
  (define-fun N0_E_m0r1c1_m0r2c1 () Bool
    false)
  (define-fun N0_E_m0r1c0_m1r1c0 () Bool
    false)
  (define-fun N0_E_m0r1c0_m0r2c0 () Bool
    false)
  (define-fun N0_E_m0r1c0_m0r1c1 () Bool
    false)
  (define-fun N0_E_m0r0c1_m1r0c1 () Bool
    false)
  (define-fun N0_E_m0r0c1_m0r1c1 () Bool
    false)
  (define-fun N0_E_m0r0c0_m1r0c0 () Bool
    false)
  (define-fun N0_E_m0r0c0_m0r1c0 () Bool
    false)
  (define-fun N0_E_m0r0c0_m0r0c1 () Bool
    false)
  (define-fun M_m2r0c0_m3r0c0 () Bool
    true)
  (define-fun N3_E_m2r0c0_m3r0c0 () Bool
    true)
  (define-fun M_m1r0c0_m2r0c0 () Bool
    true)
  (define-fun N3_E_m1r0c0_m2r0c0 () Bool
    true)
  (define-fun M_m0r0c0_m1r0c0 () Bool
    true)
  (define-fun N3_E_m0r0c0_m1r0c0 () Bool
    true)
  (define-fun M_m2r6c0_m3r6c0 () Bool
    true)
  (define-fun N0_E_m2r6c0_m3r6c0 () Bool
    true)
  (define-fun M_m1r6c0_m2r6c0 () Bool
    true)
  (define-fun N0_E_m1r6c0_m2r6c0 () Bool
    true)
  (define-fun M_m0r6c0_m1r6c0 () Bool
    true)
  (define-fun N0_E_m0r6c0_m1r6c0 () Bool
    true)
  (define-fun N2_C1_E_m3r6c0_m3r6c1 () Bool
    false)
  (define-fun N2_C0_E_m3r6c0_m3r6c1 () Bool
    false)
  (define-fun N2_E_m3r6c0_m3r6c1 () Bool
    false)
  (define-fun N2_C1_E_m3r0c0_m3r0c1 () Bool
    false)
  (define-fun N2_C0_E_m3r0c0_m3r0c1 () Bool
    false)
  (define-fun N2_E_m3r0c0_m3r0c1 () Bool
    false)
  (define-fun N2_C1_E_m2r6c1_m3r6c1 () Bool
    false)
  (define-fun N2_C0_E_m2r6c1_m3r6c1 () Bool
    false)
  (define-fun N2_E_m2r6c1_m3r6c1 () Bool
    false)
  (define-fun N2_C1_E_m2r6c0_m3r6c0 () Bool
    false)
  (define-fun N2_C0_E_m2r6c0_m3r6c0 () Bool
    false)
  (define-fun N2_E_m2r6c0_m3r6c0 () Bool
    false)
  (define-fun N2_C1_E_m2r5c1_m2r6c1 () Bool
    false)
  (define-fun N2_C0_E_m2r5c1_m2r6c1 () Bool
    false)
  (define-fun N2_E_m2r5c1_m2r6c1 () Bool
    false)
  (define-fun N2_C1_E_m2r5c0_m2r6c0 () Bool
    false)
  (define-fun N2_C0_E_m2r5c0_m2r6c0 () Bool
    false)
  (define-fun N2_E_m2r5c0_m2r6c0 () Bool
    false)
  (define-fun N2_C1_E_m2r0c1_m3r0c1 () Bool
    false)
  (define-fun N2_C0_E_m2r0c1_m3r0c1 () Bool
    false)
  (define-fun N2_E_m2r0c1_m3r0c1 () Bool
    false)
  (define-fun N2_C1_E_m2r0c1_m2r1c1 () Bool
    false)
  (define-fun N2_C0_E_m2r0c1_m2r1c1 () Bool
    false)
  (define-fun N2_E_m2r0c1_m2r1c1 () Bool
    false)
  (define-fun N2_C1_E_m2r0c0_m3r0c0 () Bool
    false)
  (define-fun N2_C0_E_m2r0c0_m3r0c0 () Bool
    false)
  (define-fun N2_E_m2r0c0_m3r0c0 () Bool
    false)
  (define-fun N2_C1_E_m2r0c0_m2r1c0 () Bool
    false)
  (define-fun N2_C0_E_m2r0c0_m2r1c0 () Bool
    false)
  (define-fun N2_E_m2r0c0_m2r1c0 () Bool
    false)
  (define-fun N2_C1_E_m1r6c1_m2r6c1 () Bool
    false)
  (define-fun N2_C0_E_m1r6c1_m2r6c1 () Bool
    false)
  (define-fun N2_E_m1r6c1_m2r6c1 () Bool
    false)
  (define-fun N2_C1_E_m1r6c0_m2r6c0 () Bool
    false)
  (define-fun N2_C0_E_m1r6c0_m2r6c0 () Bool
    false)
  (define-fun N2_E_m1r6c0_m2r6c0 () Bool
    false)
  (define-fun N2_C1_E_m1r5c1_m1r6c1 () Bool
    false)
  (define-fun N2_C0_E_m1r5c1_m1r6c1 () Bool
    false)
  (define-fun N2_E_m1r5c1_m1r6c1 () Bool
    false)
  (define-fun N2_C1_E_m1r5c0_m1r6c0 () Bool
    false)
  (define-fun N2_C0_E_m1r5c0_m1r6c0 () Bool
    false)
  (define-fun N2_E_m1r5c0_m1r6c0 () Bool
    false)
  (define-fun N2_C1_E_m1r0c1_m2r0c1 () Bool
    false)
  (define-fun N2_C0_E_m1r0c1_m2r0c1 () Bool
    false)
  (define-fun N2_E_m1r0c1_m2r0c1 () Bool
    false)
  (define-fun N2_C1_E_m1r0c1_m1r1c1 () Bool
    false)
  (define-fun N2_C0_E_m1r0c1_m1r1c1 () Bool
    false)
  (define-fun N2_E_m1r0c1_m1r1c1 () Bool
    false)
  (define-fun N2_C1_E_m1r0c0_m2r0c0 () Bool
    false)
  (define-fun N2_C0_E_m1r0c0_m2r0c0 () Bool
    false)
  (define-fun N2_E_m1r0c0_m2r0c0 () Bool
    false)
  (define-fun N2_C1_E_m1r0c0_m1r1c0 () Bool
    false)
  (define-fun N2_C0_E_m1r0c0_m1r1c0 () Bool
    false)
  (define-fun N2_E_m1r0c0_m1r1c0 () Bool
    false)
  (define-fun N2_C1_E_m0r6c1_m1r6c1 () Bool
    false)
  (define-fun N2_C0_E_m0r6c1_m1r6c1 () Bool
    false)
  (define-fun N2_E_m0r6c1_m1r6c1 () Bool
    false)
  (define-fun N2_C1_E_m0r6c0_m1r6c0 () Bool
    false)
  (define-fun N2_C0_E_m0r6c0_m1r6c0 () Bool
    false)
  (define-fun N2_E_m0r6c0_m1r6c0 () Bool
    false)
  (define-fun N2_C1_E_m0r6c0_m0r6c1 () Bool
    false)
  (define-fun N2_C0_E_m0r6c0_m0r6c1 () Bool
    false)
  (define-fun N2_E_m0r6c0_m0r6c1 () Bool
    false)
  (define-fun N2_C1_E_m0r5c1_m0r6c1 () Bool
    false)
  (define-fun N2_C0_E_m0r5c1_m0r6c1 () Bool
    false)
  (define-fun N2_E_m0r5c1_m0r6c1 () Bool
    false)
  (define-fun N2_C1_E_m0r5c0_m0r6c0 () Bool
    false)
  (define-fun N2_C0_E_m0r5c0_m0r6c0 () Bool
    false)
  (define-fun N2_E_m0r5c0_m0r6c0 () Bool
    false)
  (define-fun N2_C1_E_m0r0c1_m1r0c1 () Bool
    false)
  (define-fun N2_C0_E_m0r0c1_m1r0c1 () Bool
    false)
  (define-fun N2_E_m0r0c1_m1r0c1 () Bool
    false)
  (define-fun N2_C1_E_m0r0c1_m0r1c1 () Bool
    false)
  (define-fun N2_C0_E_m0r0c1_m0r1c1 () Bool
    false)
  (define-fun N2_E_m0r0c1_m0r1c1 () Bool
    false)
  (define-fun N2_C1_E_m0r0c0_m1r0c0 () Bool
    false)
  (define-fun N2_C0_E_m0r0c0_m1r0c0 () Bool
    false)
  (define-fun N2_E_m0r0c0_m1r0c0 () Bool
    false)
  (define-fun N2_C1_E_m0r0c0_m0r1c0 () Bool
    false)
  (define-fun N2_C0_E_m0r0c0_m0r1c0 () Bool
    false)
  (define-fun N2_E_m0r0c0_m0r1c0 () Bool
    false)
  (define-fun N2_C1_E_m0r0c0_m0r0c1 () Bool
    false)
  (define-fun N2_C0_E_m0r0c0_m0r0c1 () Bool
    false)
  (define-fun N2_E_m0r0c0_m0r0c1 () Bool
    false)
  (define-fun N1_C1_E_m3r6c0_m3r6c1 () Bool
    false)
  (define-fun N1_C0_E_m3r6c0_m3r6c1 () Bool
    false)
  (define-fun N1_E_m3r6c0_m3r6c1 () Bool
    false)
  (define-fun N1_C1_E_m3r0c0_m3r0c1 () Bool
    false)
  (define-fun N1_C0_E_m3r0c0_m3r0c1 () Bool
    false)
  (define-fun N1_E_m3r0c0_m3r0c1 () Bool
    false)
  (define-fun N1_C1_E_m2r6c1_m3r6c1 () Bool
    false)
  (define-fun N1_C0_E_m2r6c1_m3r6c1 () Bool
    false)
  (define-fun N1_E_m2r6c1_m3r6c1 () Bool
    false)
  (define-fun N1_C1_E_m2r6c0_m3r6c0 () Bool
    false)
  (define-fun N1_C0_E_m2r6c0_m3r6c0 () Bool
    false)
  (define-fun N1_E_m2r6c0_m3r6c0 () Bool
    false)
  (define-fun N1_C1_E_m2r5c1_m2r6c1 () Bool
    false)
  (define-fun N1_C0_E_m2r5c1_m2r6c1 () Bool
    false)
  (define-fun N1_E_m2r5c1_m2r6c1 () Bool
    false)
  (define-fun N1_C1_E_m2r5c0_m2r6c0 () Bool
    false)
  (define-fun N1_C0_E_m2r5c0_m2r6c0 () Bool
    false)
  (define-fun N1_E_m2r5c0_m2r6c0 () Bool
    false)
  (define-fun N1_C1_E_m2r0c1_m3r0c1 () Bool
    false)
  (define-fun N1_C0_E_m2r0c1_m3r0c1 () Bool
    false)
  (define-fun N1_E_m2r0c1_m3r0c1 () Bool
    false)
  (define-fun N1_C1_E_m2r0c1_m2r1c1 () Bool
    false)
  (define-fun N1_C0_E_m2r0c1_m2r1c1 () Bool
    false)
  (define-fun N1_E_m2r0c1_m2r1c1 () Bool
    false)
  (define-fun N1_C1_E_m2r0c0_m3r0c0 () Bool
    false)
  (define-fun N1_C0_E_m2r0c0_m3r0c0 () Bool
    false)
  (define-fun N1_E_m2r0c0_m3r0c0 () Bool
    false)
  (define-fun N1_C1_E_m2r0c0_m2r1c0 () Bool
    false)
  (define-fun N1_C0_E_m2r0c0_m2r1c0 () Bool
    false)
  (define-fun N1_E_m2r0c0_m2r1c0 () Bool
    false)
  (define-fun N1_C1_E_m1r6c1_m2r6c1 () Bool
    false)
  (define-fun N1_C0_E_m1r6c1_m2r6c1 () Bool
    false)
  (define-fun N1_E_m1r6c1_m2r6c1 () Bool
    false)
  (define-fun N1_C1_E_m1r6c0_m2r6c0 () Bool
    false)
  (define-fun N1_C0_E_m1r6c0_m2r6c0 () Bool
    false)
  (define-fun N1_E_m1r6c0_m2r6c0 () Bool
    false)
  (define-fun N1_C1_E_m1r5c1_m1r6c1 () Bool
    false)
  (define-fun N1_C0_E_m1r5c1_m1r6c1 () Bool
    false)
  (define-fun N1_E_m1r5c1_m1r6c1 () Bool
    false)
  (define-fun N1_C1_E_m1r5c0_m1r6c0 () Bool
    false)
  (define-fun N1_C0_E_m1r5c0_m1r6c0 () Bool
    false)
  (define-fun N1_E_m1r5c0_m1r6c0 () Bool
    false)
  (define-fun N1_C1_E_m1r0c1_m2r0c1 () Bool
    false)
  (define-fun N1_C0_E_m1r0c1_m2r0c1 () Bool
    false)
  (define-fun N1_E_m1r0c1_m2r0c1 () Bool
    false)
  (define-fun N1_C1_E_m1r0c1_m1r1c1 () Bool
    false)
  (define-fun N1_C0_E_m1r0c1_m1r1c1 () Bool
    false)
  (define-fun N1_E_m1r0c1_m1r1c1 () Bool
    false)
  (define-fun N1_C1_E_m1r0c0_m2r0c0 () Bool
    false)
  (define-fun N1_C0_E_m1r0c0_m2r0c0 () Bool
    false)
  (define-fun N1_E_m1r0c0_m2r0c0 () Bool
    false)
  (define-fun N1_C1_E_m1r0c0_m1r1c0 () Bool
    false)
  (define-fun N1_C0_E_m1r0c0_m1r1c0 () Bool
    false)
  (define-fun N1_E_m1r0c0_m1r1c0 () Bool
    false)
  (define-fun N1_C1_E_m0r6c1_m1r6c1 () Bool
    false)
  (define-fun N1_C0_E_m0r6c1_m1r6c1 () Bool
    false)
  (define-fun N1_E_m0r6c1_m1r6c1 () Bool
    false)
  (define-fun N1_C1_E_m0r6c0_m1r6c0 () Bool
    false)
  (define-fun N1_C0_E_m0r6c0_m1r6c0 () Bool
    false)
  (define-fun N1_E_m0r6c0_m1r6c0 () Bool
    false)
  (define-fun N1_C1_E_m0r6c0_m0r6c1 () Bool
    false)
  (define-fun N1_C0_E_m0r6c0_m0r6c1 () Bool
    false)
  (define-fun N1_E_m0r6c0_m0r6c1 () Bool
    false)
  (define-fun N1_C1_E_m0r5c1_m0r6c1 () Bool
    false)
  (define-fun N1_C0_E_m0r5c1_m0r6c1 () Bool
    false)
  (define-fun N1_E_m0r5c1_m0r6c1 () Bool
    false)
  (define-fun N1_C1_E_m0r5c0_m0r6c0 () Bool
    false)
  (define-fun N1_C0_E_m0r5c0_m0r6c0 () Bool
    false)
  (define-fun N1_E_m0r5c0_m0r6c0 () Bool
    false)
  (define-fun N1_C1_E_m0r0c1_m1r0c1 () Bool
    false)
  (define-fun N1_C0_E_m0r0c1_m1r0c1 () Bool
    false)
  (define-fun N1_E_m0r0c1_m1r0c1 () Bool
    false)
  (define-fun N1_C1_E_m0r0c1_m0r1c1 () Bool
    false)
  (define-fun N1_C0_E_m0r0c1_m0r1c1 () Bool
    false)
  (define-fun N1_E_m0r0c1_m0r1c1 () Bool
    false)
  (define-fun N1_C1_E_m0r0c0_m1r0c0 () Bool
    false)
  (define-fun N1_C0_E_m0r0c0_m1r0c0 () Bool
    false)
  (define-fun N1_E_m0r0c0_m1r0c0 () Bool
    false)
  (define-fun N1_C1_E_m0r0c0_m0r1c0 () Bool
    false)
  (define-fun N1_C0_E_m0r0c0_m0r1c0 () Bool
    false)
  (define-fun N1_E_m0r0c0_m0r1c0 () Bool
    false)
  (define-fun N1_C1_E_m0r0c0_m0r0c1 () Bool
    false)
  (define-fun N1_C0_E_m0r0c0_m0r0c1 () Bool
    false)
  (define-fun N1_E_m0r0c0_m0r0c1 () Bool
    false)
  (define-fun M_m2r5c1_pinSON () Bool
    false)
  (define-fun M_m2r5c0_pinSON () Bool
    false)
  (define-fun M_m2r4c1_pinSON () Bool
    false)
  (define-fun M_m2r4c0_pinSON () Bool
    true)
  (define-fun M_m2r3c1_pinSON () Bool
    false)
  (define-fun M_m2r3c0_pinSON () Bool
    false)
  (define-fun M_m2r2c1_pinSON () Bool
    true)
  (define-fun M_m2r2c0_pinSON () Bool
    false)
  (define-fun M_m2r1c1_pinSON () Bool
    false)
  (define-fun M_m2r1c0_pinSON () Bool
    false)
  (define-fun M_m3r6c0_pinSON_vss () Bool
    true)
  (define-fun M_m3r0c0_pinSON_vdd () Bool
    true)
  (define-fun M_m2r2c1_pin5 () Bool
    true)
  (define-fun M_m0r2c1_pin5 () Bool
    false)
  (define-fun M_m2r2c0_pin5 () Bool
    false)
  (define-fun M_m0r2c0_pin5 () Bool
    false)
  (define-fun M_m1r2c1_pin4 () Bool
    true)
  (define-fun M_m1r2c0_pin4 () Bool
    false)
  (define-fun M_m2r2c1_pin3 () Bool
    false)
  (define-fun M_m0r2c1_pin3 () Bool
    true)
  (define-fun M_m2r2c0_pin3 () Bool
    false)
  (define-fun M_m0r2c0_pin3 () Bool
    false)
  (define-fun M_m2r4c1_pin2 () Bool
    true)
  (define-fun M_m0r4c1_pin2 () Bool
    false)
  (define-fun M_m2r4c0_pin2 () Bool
    false)
  (define-fun M_m0r4c0_pin2 () Bool
    false)
  (define-fun M_m1r4c1_pin1 () Bool
    true)
  (define-fun M_m1r4c0_pin1 () Bool
    false)
  (define-fun M_m2r4c1_pin0 () Bool
    false)
  (define-fun M_m0r4c1_pin0 () Bool
    true)
  (define-fun M_m2r4c0_pin0 () Bool
    false)
  (define-fun M_m0r4c0_pin0 () Bool
    false)
  (define-fun M_m3r6c0_m3r6c1 () Bool
    true)
  (define-fun M_m3r0c0_m3r0c1 () Bool
    true)
  (define-fun M_m2r6c1_m3r6c1 () Bool
    true)
  (define-fun M_m2r5c1_m2r6c1 () Bool
    false)
  (define-fun M_m2r5c0_m2r6c0 () Bool
    false)
  (define-fun M_m2r4c1_m2r5c1 () Bool
    false)
  (define-fun M_m2r4c0_m2r5c0 () Bool
    false)
  (define-fun M_m2r3c1_m2r4c1 () Bool
    true)
  (define-fun M_m2r3c0_m2r4c0 () Bool
    true)
  (define-fun M_m2r2c1_m2r3c1 () Bool
    true)
  (define-fun M_m2r2c0_m2r3c0 () Bool
    false)
  (define-fun M_m2r1c1_m2r2c1 () Bool
    false)
  (define-fun M_m2r1c0_m2r2c0 () Bool
    false)
  (define-fun M_m2r0c1_m3r0c1 () Bool
    true)
  (define-fun M_m2r0c1_m2r1c1 () Bool
    false)
  (define-fun M_m2r0c0_m2r1c0 () Bool
    false)
  (define-fun M_m1r6c1_m2r6c1 () Bool
    true)
  (define-fun M_m1r5c1_m2r5c1 () Bool
    false)
  (define-fun M_m1r5c1_m1r6c1 () Bool
    false)
  (define-fun M_m1r5c0_m2r5c0 () Bool
    false)
  (define-fun M_m1r5c0_m1r6c0 () Bool
    false)
  (define-fun M_m1r4c1_m1r5c1 () Bool
    false)
  (define-fun M_m1r4c0_m1r5c0 () Bool
    false)
  (define-fun M_m1r3c1_m2r3c1 () Bool
    false)
  (define-fun M_m1r3c1_m1r4c1 () Bool
    true)
  (define-fun M_m1r3c0_m2r3c0 () Bool
    true)
  (define-fun M_m1r3c0_m1r4c0 () Bool
    false)
  (define-fun M_m1r2c1_m1r3c1 () Bool
    true)
  (define-fun M_m1r2c0_m1r3c0 () Bool
    false)
  (define-fun M_m1r1c1_m2r1c1 () Bool
    false)
  (define-fun M_m1r1c1_m1r2c1 () Bool
    false)
  (define-fun M_m1r1c0_m2r1c0 () Bool
    false)
  (define-fun M_m1r1c0_m1r2c0 () Bool
    false)
  (define-fun M_m1r0c1_m2r0c1 () Bool
    true)
  (define-fun M_m1r0c1_m1r1c1 () Bool
    false)
  (define-fun M_m1r0c0_m1r1c0 () Bool
    false)
  (define-fun M_m0r6c1_m1r6c1 () Bool
    true)
  (define-fun M_m0r6c0_m0r6c1 () Bool
    true)
  (define-fun M_m0r5c1_m1r5c1 () Bool
    false)
  (define-fun M_m0r5c1_m0r6c1 () Bool
    true)
  (define-fun M_m0r5c0_m1r5c0 () Bool
    false)
  (define-fun M_m0r5c0_m0r6c0 () Bool
    false)
  (define-fun M_m0r5c0_m0r5c1 () Bool
    false)
  (define-fun M_m0r4c1_m0r5c1 () Bool
    true)
  (define-fun M_m0r4c0_m0r5c0 () Bool
    false)
  (define-fun M_m0r4c0_m0r4c1 () Bool
    false)
  (define-fun M_m0r3c1_m1r3c1 () Bool
    true)
  (define-fun M_m0r3c1_m0r4c1 () Bool
    false)
  (define-fun M_m0r3c0_m1r3c0 () Bool
    true)
  (define-fun M_m0r3c0_m0r4c0 () Bool
    false)
  (define-fun M_m0r3c0_m0r3c1 () Bool
    true)
  (define-fun M_m0r2c1_m0r3c1 () Bool
    false)
  (define-fun M_m0r2c0_m0r3c0 () Bool
    false)
  (define-fun M_m0r2c0_m0r2c1 () Bool
    false)
  (define-fun M_m0r1c1_m1r1c1 () Bool
    false)
  (define-fun M_m0r1c1_m0r2c1 () Bool
    true)
  (define-fun M_m0r1c0_m1r1c0 () Bool
    false)
  (define-fun M_m0r1c0_m0r2c0 () Bool
    false)
  (define-fun M_m0r1c0_m0r1c1 () Bool
    false)
  (define-fun M_m0r0c1_m1r0c1 () Bool
    true)
  (define-fun M_m0r0c1_m0r1c1 () Bool
    true)
  (define-fun M_m0r0c0_m0r1c0 () Bool
    false)
  (define-fun M_m0r0c0_m0r0c1 () Bool
    true)
  (define-fun N3_C0_E_m3r6c0_m3r6c1 () Bool
    false)
  (define-fun N3_C0_E_m3r5c0_m3r5c1 () Bool
    false)
  (define-fun N3_C0_E_m3r4c0_m3r4c1 () Bool
    false)
  (define-fun N3_C0_E_m3r3c0_m3r3c1 () Bool
    false)
  (define-fun N3_C0_E_m2r6c1_m3r6c1 () Bool
    false)
  (define-fun N3_C0_E_m2r6c0_m3r6c0 () Bool
    false)
  (define-fun N3_C0_E_m2r5c1_m3r5c1 () Bool
    false)
  (define-fun N3_C0_E_m2r5c1_m2r6c1 () Bool
    false)
  (define-fun N3_C0_E_m2r5c0_m3r5c0 () Bool
    false)
  (define-fun N3_C0_E_m2r5c0_m2r6c0 () Bool
    false)
  (define-fun N3_C0_E_m2r4c1_m3r4c1 () Bool
    false)
  (define-fun N3_C0_E_m2r4c1_m2r5c1 () Bool
    false)
  (define-fun N3_C0_E_m2r4c0_m3r4c0 () Bool
    false)
  (define-fun N3_C0_E_m2r4c0_m2r5c0 () Bool
    false)
  (define-fun N3_C0_E_m2r3c1_m3r3c1 () Bool
    false)
  (define-fun N3_C0_E_m2r3c1_m2r4c1 () Bool
    false)
  (define-fun N3_C0_E_m2r3c0_m3r3c0 () Bool
    false)
  (define-fun N3_C0_E_m2r3c0_m2r4c0 () Bool
    false)
  (define-fun N3_C0_E_m1r6c1_m2r6c1 () Bool
    false)
  (define-fun N3_C0_E_m1r6c0_m2r6c0 () Bool
    false)
  (define-fun N3_C0_E_m1r5c1_m2r5c1 () Bool
    false)
  (define-fun N3_C0_E_m1r5c1_m1r6c1 () Bool
    false)
  (define-fun N3_C0_E_m1r5c0_m2r5c0 () Bool
    false)
  (define-fun N3_C0_E_m1r5c0_m1r6c0 () Bool
    false)
  (define-fun N3_C0_E_m1r4c1_m1r5c1 () Bool
    false)
  (define-fun N3_C0_E_m1r4c0_m1r5c0 () Bool
    false)
  (define-fun N3_C0_E_m1r3c1_m2r3c1 () Bool
    false)
  (define-fun N3_C0_E_m1r3c1_m1r4c1 () Bool
    false)
  (define-fun N3_C0_E_m1r3c0_m2r3c0 () Bool
    false)
  (define-fun N3_C0_E_m1r3c0_m1r4c0 () Bool
    false)
  (define-fun N3_C0_E_m0r6c1_m1r6c1 () Bool
    false)
  (define-fun N3_C0_E_m0r6c0_m1r6c0 () Bool
    false)
  (define-fun N3_C0_E_m0r6c0_m0r6c1 () Bool
    false)
  (define-fun N3_C0_E_m0r5c1_m1r5c1 () Bool
    false)
  (define-fun N3_C0_E_m0r5c1_m0r6c1 () Bool
    false)
  (define-fun N3_C0_E_m0r5c0_m1r5c0 () Bool
    false)
  (define-fun N3_C0_E_m0r5c0_m0r6c0 () Bool
    false)
  (define-fun N3_C0_E_m0r5c0_m0r5c1 () Bool
    false)
  (define-fun N3_C0_E_m0r4c1_m0r5c1 () Bool
    false)
  (define-fun N3_C0_E_m0r4c0_m0r5c0 () Bool
    false)
  (define-fun N3_C0_E_m0r4c0_m0r4c1 () Bool
    false)
  (define-fun N3_C0_E_m0r3c1_m1r3c1 () Bool
    false)
  (define-fun N3_C0_E_m0r3c1_m0r4c1 () Bool
    false)
  (define-fun N3_C0_E_m0r3c0_m1r3c0 () Bool
    false)
  (define-fun N3_C0_E_m0r3c0_m0r4c0 () Bool
    false)
  (define-fun N3_C0_E_m0r3c0_m0r3c1 () Bool
    false)
  (define-fun N0_C0_E_m3r3c0_m3r3c1 () Bool
    false)
  (define-fun N0_C0_E_m3r2c0_m3r2c1 () Bool
    false)
  (define-fun N0_C0_E_m3r1c0_m3r1c1 () Bool
    false)
  (define-fun N0_C0_E_m3r0c0_m3r0c1 () Bool
    false)
  (define-fun N0_C0_E_m2r3c1_m3r3c1 () Bool
    false)
  (define-fun N0_C0_E_m2r3c0_m3r3c0 () Bool
    false)
  (define-fun N0_C0_E_m2r2c1_m3r2c1 () Bool
    false)
  (define-fun N0_C0_E_m2r2c1_m2r3c1 () Bool
    false)
  (define-fun N0_C0_E_m2r2c0_m3r2c0 () Bool
    false)
  (define-fun N0_C0_E_m2r2c0_m2r3c0 () Bool
    false)
  (define-fun N0_C0_E_m2r1c1_m3r1c1 () Bool
    false)
  (define-fun N0_C0_E_m2r1c1_m2r2c1 () Bool
    false)
  (define-fun N0_C0_E_m2r1c0_m3r1c0 () Bool
    false)
  (define-fun N0_C0_E_m2r1c0_m2r2c0 () Bool
    false)
  (define-fun N0_C0_E_m2r0c1_m3r0c1 () Bool
    false)
  (define-fun N0_C0_E_m2r0c1_m2r1c1 () Bool
    false)
  (define-fun N0_C0_E_m2r0c0_m3r0c0 () Bool
    false)
  (define-fun N0_C0_E_m2r0c0_m2r1c0 () Bool
    false)
  (define-fun N0_C0_E_m1r3c1_m2r3c1 () Bool
    false)
  (define-fun N0_C0_E_m1r3c0_m2r3c0 () Bool
    false)
  (define-fun N0_C0_E_m1r2c1_m1r3c1 () Bool
    false)
  (define-fun N0_C0_E_m1r2c0_m1r3c0 () Bool
    false)
  (define-fun N0_C0_E_m1r1c1_m2r1c1 () Bool
    false)
  (define-fun N0_C0_E_m1r1c1_m1r2c1 () Bool
    false)
  (define-fun N0_C0_E_m1r1c0_m2r1c0 () Bool
    false)
  (define-fun N0_C0_E_m1r1c0_m1r2c0 () Bool
    false)
  (define-fun N0_C0_E_m1r0c1_m2r0c1 () Bool
    false)
  (define-fun N0_C0_E_m1r0c1_m1r1c1 () Bool
    false)
  (define-fun N0_C0_E_m1r0c0_m2r0c0 () Bool
    false)
  (define-fun N0_C0_E_m1r0c0_m1r1c0 () Bool
    false)
  (define-fun N0_C0_E_m0r3c1_m1r3c1 () Bool
    false)
  (define-fun N0_C0_E_m0r3c0_m1r3c0 () Bool
    false)
  (define-fun N0_C0_E_m0r3c0_m0r3c1 () Bool
    false)
  (define-fun N0_C0_E_m0r2c1_m0r3c1 () Bool
    false)
  (define-fun N0_C0_E_m0r2c0_m0r3c0 () Bool
    false)
  (define-fun N0_C0_E_m0r2c0_m0r2c1 () Bool
    false)
  (define-fun N0_C0_E_m0r1c1_m1r1c1 () Bool
    false)
  (define-fun N0_C0_E_m0r1c1_m0r2c1 () Bool
    false)
  (define-fun N0_C0_E_m0r1c0_m1r1c0 () Bool
    false)
  (define-fun N0_C0_E_m0r1c0_m0r2c0 () Bool
    false)
  (define-fun N0_C0_E_m0r1c0_m0r1c1 () Bool
    false)
  (define-fun N0_C0_E_m0r0c1_m1r0c1 () Bool
    false)
  (define-fun N0_C0_E_m0r0c1_m0r1c1 () Bool
    false)
  (define-fun N0_C0_E_m0r0c0_m1r0c0 () Bool
    false)
  (define-fun N0_C0_E_m0r0c0_m0r1c0 () Bool
    false)
  (define-fun N0_C0_E_m0r0c0_m0r0c1 () Bool
    false)
  (define-fun N0_E_m3r6c0_pinSON_vss () Bool
    true)
  (define-fun N3_E_m3r0c0_pinSON_vdd () Bool
    true)
  (define-fun C_N2_c1_pin5 () Bool
    true)
  (define-fun C_N2_c0_pin5 () Bool
    false)
  (define-fun C_N1_c1_pin4 () Bool
    true)
  (define-fun C_N1_c0_pin4 () Bool
    false)
  (define-fun C_N3_c1_pin3 () Bool
    true)
  (define-fun C_N3_c0_pin3 () Bool
    false)
  (define-fun C_N2_c1_pin2 () Bool
    true)
  (define-fun C_N2_c0_pin2 () Bool
    false)
  (define-fun C_N1_c1_pin1 () Bool
    true)
  (define-fun C_N1_c0_pin1 () Bool
    false)
  (define-fun C_N0_c1_pin0 () Bool
    true)
  (define-fun C_N0_c0_pin0 () Bool
    false)
  (define-fun C_N3_m3r6c1 () Bool
    false)
  (define-fun C_N2_m3r6c1 () Bool
    false)
  (define-fun C_N1_m3r6c1 () Bool
    false)
  (define-fun C_N0_m3r6c1 () Bool
    true)
  (define-fun N0_E_m3r6c0_m3r6c1 () Bool
    true)
  (define-fun C_N3_m3r6c0 () Bool
    false)
  (define-fun C_N2_m3r6c0 () Bool
    false)
  (define-fun C_N1_m3r6c0 () Bool
    false)
  (define-fun C_N0_m3r6c0 () Bool
    true)
  (define-fun C_N3_m3r5c1 () Bool
    false)
  (define-fun C_N2_m3r5c1 () Bool
    false)
  (define-fun C_N1_m3r5c1 () Bool
    false)
  (define-fun C_N0_m3r5c1 () Bool
    false)
  (define-fun C_N3_m3r5c0 () Bool
    false)
  (define-fun C_N2_m3r5c0 () Bool
    false)
  (define-fun C_N1_m3r5c0 () Bool
    false)
  (define-fun C_N0_m3r5c0 () Bool
    false)
  (define-fun C_N3_m3r4c1 () Bool
    false)
  (define-fun C_N2_m3r4c1 () Bool
    false)
  (define-fun C_N1_m3r4c1 () Bool
    false)
  (define-fun C_N0_m3r4c1 () Bool
    false)
  (define-fun C_N3_m3r4c0 () Bool
    false)
  (define-fun C_N2_m3r4c0 () Bool
    false)
  (define-fun C_N1_m3r4c0 () Bool
    false)
  (define-fun C_N0_m3r4c0 () Bool
    false)
  (define-fun C_N3_m3r3c1 () Bool
    false)
  (define-fun C_N2_m3r3c1 () Bool
    false)
  (define-fun C_N1_m3r3c1 () Bool
    false)
  (define-fun C_N0_m3r3c1 () Bool
    false)
  (define-fun C_N3_m3r3c0 () Bool
    false)
  (define-fun C_N2_m3r3c0 () Bool
    false)
  (define-fun C_N1_m3r3c0 () Bool
    false)
  (define-fun C_N0_m3r3c0 () Bool
    false)
  (define-fun C_N3_m3r2c1 () Bool
    false)
  (define-fun C_N2_m3r2c1 () Bool
    false)
  (define-fun C_N1_m3r2c1 () Bool
    false)
  (define-fun C_N0_m3r2c1 () Bool
    false)
  (define-fun C_N3_m3r2c0 () Bool
    false)
  (define-fun C_N2_m3r2c0 () Bool
    false)
  (define-fun C_N1_m3r2c0 () Bool
    false)
  (define-fun C_N0_m3r2c0 () Bool
    false)
  (define-fun C_N3_m3r1c1 () Bool
    false)
  (define-fun C_N2_m3r1c1 () Bool
    false)
  (define-fun C_N1_m3r1c1 () Bool
    false)
  (define-fun C_N0_m3r1c1 () Bool
    false)
  (define-fun C_N3_m3r1c0 () Bool
    false)
  (define-fun C_N2_m3r1c0 () Bool
    false)
  (define-fun C_N1_m3r1c0 () Bool
    false)
  (define-fun C_N0_m3r1c0 () Bool
    false)
  (define-fun C_N3_m3r0c1 () Bool
    true)
  (define-fun N3_E_m3r0c0_m3r0c1 () Bool
    true)
  (define-fun C_N2_m3r0c1 () Bool
    false)
  (define-fun C_N1_m3r0c1 () Bool
    false)
  (define-fun C_N0_m3r0c1 () Bool
    false)
  (define-fun C_N3_m3r0c0 () Bool
    true)
  (define-fun C_N2_m3r0c0 () Bool
    false)
  (define-fun C_N1_m3r0c0 () Bool
    false)
  (define-fun C_N0_m3r0c0 () Bool
    false)
  (define-fun C_N3_m2r6c1 () Bool
    false)
  (define-fun C_N2_m2r6c1 () Bool
    false)
  (define-fun C_N1_m2r6c1 () Bool
    false)
  (define-fun C_N0_m2r6c1 () Bool
    true)
  (define-fun N0_E_m2r6c1_m3r6c1 () Bool
    true)
  (define-fun C_N3_m2r6c0 () Bool
    false)
  (define-fun C_N2_m2r6c0 () Bool
    false)
  (define-fun C_N1_m2r6c0 () Bool
    false)
  (define-fun C_N0_m2r6c0 () Bool
    true)
  (define-fun C_N3_m2r5c1 () Bool
    false)
  (define-fun C_N2_m2r5c1 () Bool
    false)
  (define-fun N2_E_m2r5c1_pinSON () Bool
    false)
  (define-fun C_N1_m2r5c1 () Bool
    false)
  (define-fun N1_E_m2r5c1_pinSON () Bool
    false)
  (define-fun C_N0_m2r5c1 () Bool
    false)
  (define-fun C_N3_m2r5c0 () Bool
    false)
  (define-fun C_N2_m2r5c0 () Bool
    false)
  (define-fun N2_E_m2r5c0_pinSON () Bool
    false)
  (define-fun C_N1_m2r5c0 () Bool
    false)
  (define-fun N1_E_m2r5c0_pinSON () Bool
    false)
  (define-fun C_N0_m2r5c0 () Bool
    false)
  (define-fun C_N3_m2r4c1 () Bool
    false)
  (define-fun C_N2_m2r4c1 () Bool
    true)
  (define-fun N2_E_m2r4c1_pinSON () Bool
    false)
  (define-fun N2_E_m2r4c1_pin2 () Bool
    true)
  (define-fun C_N1_m2r4c1 () Bool
    false)
  (define-fun N1_E_m2r4c1_pinSON () Bool
    false)
  (define-fun C_N0_m2r4c1 () Bool
    false)
  (define-fun N0_E_m2r4c1_pin0 () Bool
    false)
  (define-fun C_N3_m2r4c0 () Bool
    false)
  (define-fun C_N2_m2r4c0 () Bool
    false)
  (define-fun N2_E_m2r4c0_pinSON () Bool
    false)
  (define-fun N2_E_m2r4c0_pin2 () Bool
    false)
  (define-fun C_N1_m2r4c0 () Bool
    true)
  (define-fun N1_E_m2r4c0_pinSON () Bool
    true)
  (define-fun C_N0_m2r4c0 () Bool
    false)
  (define-fun N0_E_m2r4c0_pin0 () Bool
    false)
  (define-fun C_N3_m2r3c1 () Bool
    false)
  (define-fun C_N2_m2r3c1 () Bool
    true)
  (define-fun N2_E_m2r3c1_pinSON () Bool
    false)
  (define-fun C_N1_m2r3c1 () Bool
    false)
  (define-fun N1_E_m2r3c1_pinSON () Bool
    false)
  (define-fun C_N0_m2r3c1 () Bool
    false)
  (define-fun C_N3_m2r3c0 () Bool
    false)
  (define-fun C_N2_m2r3c0 () Bool
    false)
  (define-fun N2_E_m2r3c0_pinSON () Bool
    false)
  (define-fun C_N1_m2r3c0 () Bool
    true)
  (define-fun N1_E_m2r3c0_pinSON () Bool
    false)
  (define-fun C_N0_m2r3c0 () Bool
    false)
  (define-fun C_N3_m2r2c1 () Bool
    false)
  (define-fun N3_E_m2r2c1_pin3 () Bool
    false)
  (define-fun C_N2_m2r2c1 () Bool
    true)
  (define-fun N2_E_m2r2c1_pinSON () Bool
    true)
  (define-fun N2_E_m2r2c1_pin5 () Bool
    true)
  (define-fun C_N1_m2r2c1 () Bool
    false)
  (define-fun N1_E_m2r2c1_pinSON () Bool
    false)
  (define-fun C_N0_m2r2c1 () Bool
    false)
  (define-fun C_N3_m2r2c0 () Bool
    false)
  (define-fun N3_E_m2r2c0_pin3 () Bool
    false)
  (define-fun C_N2_m2r2c0 () Bool
    false)
  (define-fun N2_E_m2r2c0_pinSON () Bool
    false)
  (define-fun N2_E_m2r2c0_pin5 () Bool
    false)
  (define-fun C_N1_m2r2c0 () Bool
    false)
  (define-fun N1_E_m2r2c0_pinSON () Bool
    false)
  (define-fun C_N0_m2r2c0 () Bool
    false)
  (define-fun C_N3_m2r1c1 () Bool
    false)
  (define-fun C_N2_m2r1c1 () Bool
    false)
  (define-fun N2_E_m2r1c1_pinSON () Bool
    false)
  (define-fun C_N1_m2r1c1 () Bool
    false)
  (define-fun N1_E_m2r1c1_pinSON () Bool
    false)
  (define-fun C_N0_m2r1c1 () Bool
    false)
  (define-fun C_N3_m2r1c0 () Bool
    false)
  (define-fun C_N2_m2r1c0 () Bool
    false)
  (define-fun N2_E_m2r1c0_pinSON () Bool
    false)
  (define-fun C_N1_m2r1c0 () Bool
    false)
  (define-fun N1_E_m2r1c0_pinSON () Bool
    false)
  (define-fun C_N0_m2r1c0 () Bool
    false)
  (define-fun C_N3_m2r0c1 () Bool
    true)
  (define-fun N3_E_m2r0c1_m3r0c1 () Bool
    true)
  (define-fun C_N2_m2r0c1 () Bool
    false)
  (define-fun C_N1_m2r0c1 () Bool
    false)
  (define-fun C_N0_m2r0c1 () Bool
    false)
  (define-fun C_N3_m2r0c0 () Bool
    true)
  (define-fun C_N2_m2r0c0 () Bool
    false)
  (define-fun C_N1_m2r0c0 () Bool
    false)
  (define-fun C_N0_m2r0c0 () Bool
    false)
  (define-fun C_N3_m1r6c1 () Bool
    false)
  (define-fun C_N2_m1r6c1 () Bool
    false)
  (define-fun C_N1_m1r6c1 () Bool
    false)
  (define-fun C_N0_m1r6c1 () Bool
    true)
  (define-fun N0_E_m1r6c1_m2r6c1 () Bool
    true)
  (define-fun C_N3_m1r6c0 () Bool
    false)
  (define-fun C_N2_m1r6c0 () Bool
    false)
  (define-fun C_N1_m1r6c0 () Bool
    false)
  (define-fun C_N0_m1r6c0 () Bool
    true)
  (define-fun C_N3_m1r5c1 () Bool
    false)
  (define-fun C_N2_m1r5c1 () Bool
    false)
  (define-fun C_N1_m1r5c1 () Bool
    false)
  (define-fun C_N0_m1r5c1 () Bool
    false)
  (define-fun C_N3_m1r5c0 () Bool
    false)
  (define-fun C_N2_m1r5c0 () Bool
    false)
  (define-fun C_N1_m1r5c0 () Bool
    false)
  (define-fun C_N0_m1r5c0 () Bool
    false)
  (define-fun C_N3_m1r4c1 () Bool
    false)
  (define-fun C_N2_m1r4c1 () Bool
    false)
  (define-fun C_N1_m1r4c1 () Bool
    true)
  (define-fun N1_E_m1r4c1_pin1 () Bool
    true)
  (define-fun C_N0_m1r4c1 () Bool
    false)
  (define-fun C_N3_m1r4c0 () Bool
    false)
  (define-fun C_N2_m1r4c0 () Bool
    false)
  (define-fun C_N1_m1r4c0 () Bool
    false)
  (define-fun N1_E_m1r4c0_pin1 () Bool
    false)
  (define-fun C_N0_m1r4c0 () Bool
    false)
  (define-fun C_N3_m1r3c1 () Bool
    false)
  (define-fun C_N2_m1r3c1 () Bool
    false)
  (define-fun C_N1_m1r3c1 () Bool
    true)
  (define-fun C_N0_m1r3c1 () Bool
    false)
  (define-fun C_N3_m1r3c0 () Bool
    false)
  (define-fun C_N2_m1r3c0 () Bool
    false)
  (define-fun C_N1_m1r3c0 () Bool
    true)
  (define-fun C_N0_m1r3c0 () Bool
    false)
  (define-fun C_N3_m1r2c1 () Bool
    false)
  (define-fun C_N2_m1r2c1 () Bool
    false)
  (define-fun C_N1_m1r2c1 () Bool
    true)
  (define-fun N1_E_m1r2c1_pin4 () Bool
    true)
  (define-fun C_N0_m1r2c1 () Bool
    false)
  (define-fun C_N3_m1r2c0 () Bool
    false)
  (define-fun C_N2_m1r2c0 () Bool
    false)
  (define-fun C_N1_m1r2c0 () Bool
    false)
  (define-fun N1_E_m1r2c0_pin4 () Bool
    false)
  (define-fun C_N0_m1r2c0 () Bool
    false)
  (define-fun C_N3_m1r1c1 () Bool
    false)
  (define-fun C_N2_m1r1c1 () Bool
    false)
  (define-fun C_N1_m1r1c1 () Bool
    false)
  (define-fun C_N0_m1r1c1 () Bool
    false)
  (define-fun C_N3_m1r1c0 () Bool
    false)
  (define-fun C_N2_m1r1c0 () Bool
    false)
  (define-fun C_N1_m1r1c0 () Bool
    false)
  (define-fun C_N0_m1r1c0 () Bool
    false)
  (define-fun C_N3_m1r0c1 () Bool
    true)
  (define-fun N3_E_m1r0c1_m2r0c1 () Bool
    true)
  (define-fun C_N2_m1r0c1 () Bool
    false)
  (define-fun C_N1_m1r0c1 () Bool
    false)
  (define-fun C_N0_m1r0c1 () Bool
    false)
  (define-fun C_N3_m1r0c0 () Bool
    true)
  (define-fun C_N2_m1r0c0 () Bool
    false)
  (define-fun C_N1_m1r0c0 () Bool
    false)
  (define-fun C_N0_m1r0c0 () Bool
    false)
  (define-fun C_N3_m0r6c1 () Bool
    false)
  (define-fun C_N2_m0r6c1 () Bool
    false)
  (define-fun C_N1_m0r6c1 () Bool
    false)
  (define-fun C_N0_m0r6c1 () Bool
    true)
  (define-fun N0_E_m0r6c1_m1r6c1 () Bool
    true)
  (define-fun N0_E_m0r6c0_m0r6c1 () Bool
    true)
  (define-fun C_N3_m0r6c0 () Bool
    false)
  (define-fun C_N2_m0r6c0 () Bool
    false)
  (define-fun C_N1_m0r6c0 () Bool
    false)
  (define-fun C_N0_m0r6c0 () Bool
    true)
  (define-fun C_N3_m0r5c1 () Bool
    false)
  (define-fun C_N2_m0r5c1 () Bool
    false)
  (define-fun C_N1_m0r5c1 () Bool
    false)
  (define-fun C_N0_m0r5c1 () Bool
    true)
  (define-fun C_N3_m0r5c0 () Bool
    false)
  (define-fun C_N2_m0r5c0 () Bool
    false)
  (define-fun C_N1_m0r5c0 () Bool
    false)
  (define-fun C_N0_m0r5c0 () Bool
    false)
  (define-fun C_N3_m0r4c1 () Bool
    false)
  (define-fun C_N2_m0r4c1 () Bool
    false)
  (define-fun N2_E_m0r4c1_pin2 () Bool
    false)
  (define-fun C_N1_m0r4c1 () Bool
    false)
  (define-fun C_N0_m0r4c1 () Bool
    true)
  (define-fun N0_E_m0r4c1_pin0 () Bool
    true)
  (define-fun C_N3_m0r4c0 () Bool
    false)
  (define-fun C_N2_m0r4c0 () Bool
    false)
  (define-fun N2_E_m0r4c0_pin2 () Bool
    false)
  (define-fun C_N1_m0r4c0 () Bool
    false)
  (define-fun C_N0_m0r4c0 () Bool
    false)
  (define-fun N0_E_m0r4c0_pin0 () Bool
    false)
  (define-fun C_N3_m0r3c1 () Bool
    false)
  (define-fun C_N2_m0r3c1 () Bool
    false)
  (define-fun C_N1_m0r3c1 () Bool
    true)
  (define-fun C_N0_m0r3c1 () Bool
    false)
  (define-fun C_N3_m0r3c0 () Bool
    false)
  (define-fun C_N2_m0r3c0 () Bool
    false)
  (define-fun C_N1_m0r3c0 () Bool
    true)
  (define-fun C_N0_m0r3c0 () Bool
    false)
  (define-fun C_N3_m0r2c1 () Bool
    true)
  (define-fun N3_E_m0r2c1_pin3 () Bool
    true)
  (define-fun C_N2_m0r2c1 () Bool
    false)
  (define-fun N2_E_m0r2c1_pin5 () Bool
    false)
  (define-fun C_N1_m0r2c1 () Bool
    false)
  (define-fun C_N0_m0r2c1 () Bool
    false)
  (define-fun C_N3_m0r2c0 () Bool
    false)
  (define-fun N3_E_m0r2c0_pin3 () Bool
    false)
  (define-fun C_N2_m0r2c0 () Bool
    false)
  (define-fun N2_E_m0r2c0_pin5 () Bool
    false)
  (define-fun C_N1_m0r2c0 () Bool
    false)
  (define-fun C_N0_m0r2c0 () Bool
    false)
  (define-fun C_N3_m0r1c1 () Bool
    true)
  (define-fun C_N2_m0r1c1 () Bool
    false)
  (define-fun C_N1_m0r1c1 () Bool
    false)
  (define-fun C_N0_m0r1c1 () Bool
    false)
  (define-fun C_N3_m0r1c0 () Bool
    false)
  (define-fun C_N2_m0r1c0 () Bool
    false)
  (define-fun C_N1_m0r1c0 () Bool
    false)
  (define-fun C_N0_m0r1c0 () Bool
    false)
  (define-fun C_N3_m0r0c1 () Bool
    true)
  (define-fun N3_E_m0r0c1_m1r0c1 () Bool
    true)
  (define-fun N3_E_m0r0c0_m0r0c1 () Bool
    true)
  (define-fun COST_SIZE () (_ BitVec 3)
    #b001)
  (define-fun COST_SIZE_N () (_ BitVec 3)
    #b001)
  (define-fun COST_SIZE_P () (_ BitVec 3)
    #b001)
  (define-fun C_N2_m0r0c1 () Bool
    false)
  (define-fun C_N1_m0r0c1 () Bool
    false)
  (define-fun C_N0_m0r0c1 () Bool
    false)
  (define-fun C_N3_m0r0c0 () Bool
    true)
  (define-fun C_N2_m0r0c0 () Bool
    false)
  (define-fun C_N1_m0r0c0 () Bool
    false)
  (define-fun C_N0_m0r0c0 () Bool
    false)
  (define-fun N3_C0_E_m3r0c0_pinSON_vdd () Bool
    true)
  (define-fun C_N3_C0_c1_pin3 () Bool
    true)
  (define-fun C_N3_C0_c0_pin3 () Bool
    false)
  (define-fun C_N2_C1_c1_pin5 () Bool
    true)
  (define-fun C_N2_C1_c0_pin5 () Bool
    false)
  (define-fun C_N2_C1_c1_pin2 () Bool
    true)
  (define-fun C_N2_C1_c0_pin2 () Bool
    false)
  (define-fun C_N2_C0_c1_pin2 () Bool
    true)
  (define-fun C_N2_C0_c0_pin2 () Bool
    false)
  (define-fun C_N1_C1_c1_pin4 () Bool
    true)
  (define-fun C_N1_C1_c0_pin4 () Bool
    false)
  (define-fun C_N1_C1_c1_pin1 () Bool
    true)
  (define-fun C_N1_C1_c0_pin1 () Bool
    false)
  (define-fun C_N1_C0_c1_pin1 () Bool
    true)
  (define-fun C_N1_C0_c0_pin1 () Bool
    false)
  (define-fun N0_C0_E_m3r6c0_pinSON_vss () Bool
    true)
  (define-fun C_N0_C0_c1_pin0 () Bool
    true)
  (define-fun C_N0_C0_c0_pin0 () Bool
    false)
  (define-fun N3_C0_E_m2r2c1_m2r3c1 () Bool
    false)
  (define-fun N3_C0_E_m2r2c0_m2r3c0 () Bool
    false)
  (define-fun N3_C0_E_m1r2c1_m1r3c1 () Bool
    false)
  (define-fun N3_C0_E_m1r2c0_m1r3c0 () Bool
    false)
  (define-fun N3_C0_E_m1r1c1_m1r2c1 () Bool
    false)
  (define-fun N3_C0_E_m1r1c0_m1r2c0 () Bool
    false)
  (define-fun N3_C0_E_m0r2c1_m0r3c1 () Bool
    false)
  (define-fun N3_C0_E_m0r2c0_m0r3c0 () Bool
    false)
  (define-fun N0_C0_E_m2r3c1_m2r4c1 () Bool
    false)
  (define-fun N0_C0_E_m2r3c0_m2r4c0 () Bool
    false)
  (define-fun N0_C0_E_m1r4c1_m1r5c1 () Bool
    false)
  (define-fun N0_C0_E_m1r4c0_m1r5c0 () Bool
    false)
  (define-fun N0_C0_E_m1r3c1_m1r4c1 () Bool
    false)
  (define-fun N0_C0_E_m1r3c0_m1r4c0 () Bool
    false)
  (define-fun N0_C0_E_m0r3c1_m0r4c1 () Bool
    false)
  (define-fun N0_C0_E_m0r3c0_m0r4c0 () Bool
    false)
  (define-fun N1_C1_E_m1r2c1_pin4 () Bool
    true)
  (define-fun N1_C1_E_m1r2c0_pin4 () Bool
    false)
  (define-fun N1_C1_E_m1r4c1_pin1 () Bool
    true)
  (define-fun N1_C1_E_m1r4c0_pin1 () Bool
    false)
  (define-fun N1_C0_E_m1r4c1_pin1 () Bool
    true)
  (define-fun N1_C0_E_m1r4c0_pin1 () Bool
    false)
  (define-fun N2_LM_TRACK () Bool
    false)
  (define-fun N2_LM_TRACK_6 () Bool
    false)
  (define-fun N2_LM_TRACK_5 () Bool
    false)
  (define-fun N2_LM_TRACK_4 () Bool
    false)
  (define-fun N2_LM_TRACK_3 () Bool
    false)
  (define-fun N2_LM_TRACK_2 () Bool
    false)
  (define-fun N2_LM_TRACK_1 () Bool
    false)
  (define-fun N2_LM_TRACK_0 () Bool
    false)
  (define-fun N1_LM_TRACK () Bool
    false)
  (define-fun N1_LM_TRACK_6 () Bool
    false)
  (define-fun N1_LM_TRACK_5 () Bool
    false)
  (define-fun N1_LM_TRACK_4 () Bool
    false)
  (define-fun N1_LM_TRACK_3 () Bool
    false)
  (define-fun N1_LM_TRACK_2 () Bool
    false)
  (define-fun N1_LM_TRACK_1 () Bool
    false)
  (define-fun N1_LM_TRACK_0 () Bool
    false)
  (define-fun LM_TRACK_6 () Bool
    false)
  (define-fun LM_TRACK_5 () Bool
    false)
  (define-fun M_m3r5c0_m3r5c1 () Bool
    false)
  (define-fun M_m2r5c1_m3r5c1 () Bool
    false)
  (define-fun M_m2r5c0_m3r5c0 () Bool
    false)
  (define-fun LM_TRACK_4 () Bool
    false)
  (define-fun M_m3r4c0_m3r4c1 () Bool
    false)
  (define-fun M_m2r4c1_m3r4c1 () Bool
    false)
  (define-fun M_m2r4c0_m3r4c0 () Bool
    false)
  (define-fun LM_TRACK_3 () Bool
    false)
  (define-fun M_m3r3c0_m3r3c1 () Bool
    false)
  (define-fun M_m2r3c1_m3r3c1 () Bool
    false)
  (define-fun M_m2r3c0_m3r3c0 () Bool
    false)
  (define-fun LM_TRACK_2 () Bool
    false)
  (define-fun M_m3r2c0_m3r2c1 () Bool
    false)
  (define-fun M_m2r2c1_m3r2c1 () Bool
    false)
  (define-fun M_m2r2c0_m3r2c0 () Bool
    false)
  (define-fun LM_TRACK_1 () Bool
    false)
  (define-fun M_m3r1c0_m3r1c1 () Bool
    false)
  (define-fun M_m2r1c1_m3r1c1 () Bool
    false)
  (define-fun M_m2r1c0_m3r1c0 () Bool
    false)
  (define-fun LM_TRACK_0 () Bool
    false)
  (define-fun y1 () (_ BitVec 4)
    #x4)
  (define-fun y0 () (_ BitVec 4)
    #x2)
  (define-fun t1 () (_ BitVec 2)
    #b00)
  (define-fun t0 () (_ BitVec 2)
    #b00)
  (define-fun numTier () (_ BitVec 2)
    #b01)
  (define-fun trackNFET () (_ BitVec 4)
    #x4)
  (define-fun trackPFET () (_ BitVec 4)
    #x2)
  (define-fun trackH () (_ BitVec 4)
    #x7)
)
(objectives
 (COST_SIZE 1)
 ((bvadd t0 t1) 0)
 ((bvadd N1_C0 N1_C1 N2_C0 N2_C1) 2)
 ((bvadd N1_R1 N1_R2 N1_R3 N1_R4 N1_R5 N2_R1 N2_R2 N2_R3 N2_R4 N2_R5) 0)
 ((bvadd (ite (= LM_TRACK_0 true) #x1 #x0)
       (ite (= LM_TRACK_1 true) #x1 #x0)
       (ite (= LM_TRACK_2 true) #x1 #x0)
       (ite (= LM_TRACK_3 true) #x1 #x0)
       (ite (= LM_TRACK_4 true) #x1 #x0)
       (ite (= LM_TRACK_5 true) #x1 #x0)
       (ite (= LM_TRACK_6 true) #x1 #x0)) 0)
 ((bvadd (ite (= M_m3r1c0_m3r1c1 true) #x00000001 #x00000000)
       (ite (= M_m3r2c0_m3r2c1 true) #x00000001 #x00000000)
       (ite (= M_m3r3c0_m3r3c1 true) #x00000001 #x00000000)
       (ite (= M_m3r4c0_m3r4c1 true) #x00000001 #x00000000)
       (ite (= M_m3r5c0_m3r5c1 true) #x00000001 #x00000000)) 0)
 ((bvadd (ite (= M_m0r1c0_m1r1c0 true) #x00000001 #x00000000)
       (ite (= M_m0r1c1_m1r1c1 true) #x00000001 #x00000000)
       (ite (= M_m0r3c0_m1r3c0 true) #x00000001 #x00000000)
       (ite (= M_m0r3c1_m1r3c1 true) #x00000001 #x00000000)
       (ite (= M_m0r5c0_m1r5c0 true) #x00000001 #x00000000)
       (ite (= M_m0r5c1_m1r5c1 true) #x00000001 #x00000000)) 2)
 ((bvadd (ite (= M_m0r0c0_m0r1c0 true) #x00000001 #x00000000)
       (ite (= M_m0r0c1_m0r1c1 true) #x00000001 #x00000000)
       (ite (= M_m0r1c0_m0r1c1 true) #x00000001 #x00000000)
       (ite (= M_m0r1c0_m0r2c0 true) #x00000001 #x00000000)
       (ite (= M_m0r1c1_m0r2c1 true) #x00000001 #x00000000)
       (ite (= M_m0r2c0_m0r2c1 true) #x00000001 #x00000000)
       (ite (= M_m0r2c0_m0r3c0 true) #x00000001 #x00000000)
       (ite (= M_m0r2c1_m0r3c1 true) #x00000001 #x00000000)
       (ite (= M_m0r3c0_m0r3c1 true) #x00000001 #x00000000)
       (ite (= M_m0r3c0_m0r4c0 true) #x00000001 #x00000000)
       (ite (= M_m0r3c1_m0r4c1 true) #x00000001 #x00000000)
       (ite (= M_m0r4c0_m0r4c1 true) #x00000001 #x00000000)
       (ite (= M_m0r4c0_m0r5c0 true) #x00000001 #x00000000)
       (ite (= M_m0r4c1_m0r5c1 true) #x00000001 #x00000000)
       (ite (= M_m0r5c0_m0r5c1 true) #x00000001 #x00000000)
       (ite (= M_m0r5c0_m0r6c0 true) #x00000001 #x00000000)
       (ite (= M_m0r5c1_m0r6c1 true) #x00000001 #x00000000)) 5)
 ((bvadd (ite (= M_m1r1c0_m2r1c0 true) #x00000001 #x00000000)
       (ite (= M_m1r1c1_m2r1c1 true) #x00000001 #x00000000)
       (ite (= M_m1r3c0_m2r3c0 true) #x00000001 #x00000000)
       (ite (= M_m1r3c1_m2r3c1 true) #x00000001 #x00000000)
       (ite (= M_m1r5c0_m2r5c0 true) #x00000001 #x00000000)
       (ite (= M_m1r5c1_m2r5c1 true) #x00000001 #x00000000)) 1)
 ((bvadd (ite (= M_m1r0c0_m1r1c0 true) #x00000001 #x00000000)
       (ite (= M_m1r0c1_m1r1c1 true) #x00000001 #x00000000)
       (ite (= M_m1r1c0_m1r2c0 true) #x00000001 #x00000000)
       (ite (= M_m1r1c1_m1r2c1 true) #x00000001 #x00000000)
       (ite (= M_m1r2c0_m1r3c0 true) #x00000001 #x00000000)
       (ite (= M_m1r2c1_m1r3c1 true) #x00000001 #x00000000)
       (ite (= M_m1r3c0_m1r4c0 true) #x00000001 #x00000000)
       (ite (= M_m1r3c1_m1r4c1 true) #x00000001 #x00000000)
       (ite (= M_m1r4c0_m1r5c0 true) #x00000001 #x00000000)
       (ite (= M_m1r4c1_m1r5c1 true) #x00000001 #x00000000)
       (ite (= M_m1r5c0_m1r6c0 true) #x00000001 #x00000000)
       (ite (= M_m1r5c1_m1r6c1 true) #x00000001 #x00000000)) 2)
 ((bvadd (ite (= M_m2r1c0_m3r1c0 true) #x00000001 #x00000000)
       (ite (= M_m2r1c1_m3r1c1 true) #x00000001 #x00000000)
       (ite (= M_m2r2c0_m3r2c0 true) #x00000001 #x00000000)
       (ite (= M_m2r2c1_m3r2c1 true) #x00000001 #x00000000)
       (ite (= M_m2r3c0_m3r3c0 true) #x00000001 #x00000000)
       (ite (= M_m2r3c1_m3r3c1 true) #x00000001 #x00000000)
       (ite (= M_m2r4c0_m3r4c0 true) #x00000001 #x00000000)
       (ite (= M_m2r4c1_m3r4c1 true) #x00000001 #x00000000)
       (ite (= M_m2r5c0_m3r5c0 true) #x00000001 #x00000000)
       (ite (= M_m2r5c1_m3r5c1 true) #x00000001 #x00000000)) 0)
 ((bvadd (ite (= M_m2r0c0_m2r1c0 true) #x00000001 #x00000000)
       (ite (= M_m2r0c1_m2r1c1 true) #x00000001 #x00000000)
       (ite (= M_m2r1c0_m2r2c0 true) #x00000001 #x00000000)
       (ite (= M_m2r1c1_m2r2c1 true) #x00000001 #x00000000)
       (ite (= M_m2r2c0_m2r3c0 true) #x00000001 #x00000000)
       (ite (= M_m2r2c1_m2r3c1 true) #x00000001 #x00000000)
       (ite (= M_m2r3c0_m2r4c0 true) #x00000001 #x00000000)
       (ite (= M_m2r3c1_m2r4c1 true) #x00000001 #x00000000)
       (ite (= M_m2r4c0_m2r5c0 true) #x00000001 #x00000000)
       (ite (= M_m2r4c1_m2r5c1 true) #x00000001 #x00000000)
       (ite (= M_m2r5c0_m2r6c0 true) #x00000001 #x00000000)
       (ite (= M_m2r5c1_m2r6c1 true) #x00000001 #x00000000)) 3)
)
(:eliminated-vars         864
 :max-memory              49.76
 :memory                  49.52
 :num-allocs              40032994
 :pb-conflicts            8
 :pb-lemmas               3
 :pb-propagations         650
 :pb-resolves             30
 :pb-subsumes             8
 :rlimit-count            925264
 :sat-backjumps           703
 :sat-conflicts           714
 :sat-decisions           4055
 :sat-del-clause          945
 :sat-elim-clauses        679
 :sat-elim-literals       4102
 :sat-minimized-lits      1805
 :sat-mk-clause-2ary      3872
 :sat-mk-clause-3ary      2496
 :sat-mk-clause-nary      1239
 :sat-mk-var              2008
 :sat-probing-assigned    136
 :sat-propagations-2ary   127297
 :sat-propagations-3ary   42618
 :sat-propagations-nary   15763
 :sat-restarts            1
 :sat-scc-elim-binary     31
 :sat-scc-elim-vars       112
 :sat-subs-resolution     140
 :sat-subs-resolution-dyn 78
 :sat-subsumed            137
 :sat-units               1575
 :time                    0.07
 :total-time              0.10)
